### ISSUE TITLE
Question about IR projector and resulting point cloud

### ISSUE THREAD

**Issue by Tabjones** [code-iai/iai_kinect2#100]
Hi, this is more a question than an issue, but i think it was worth it to share with you.

I found out that sometimes covering the IR projector with a 'semi-transparent' tape could improve the resulting point cloud quality. Take a look a this picture i made:
![screenshot from 2015-05-28 12 14 40](https://cloud.githubusercontent.com/assets/1950251/7857854/30a159aa-0534-11e5-833a-3826739ec6b3.png)

Left pic has a tape covering the IR projector, right hasn't. As you can see border of objects are much more defined in the left image, especially around the pot handle and the pattern right border.
However, covering the projector, sensibly reduces IR range: left image has no floor and almost no objects on the background.

I was wondering why my uncovered point cloud has such high level of noise around the borders. and yours hasn't!

  * Do you guys have covered the projector?
  * Is it because i have made a poor calibration ?
  * Is it becasue i have some strange/bad illumination in the room ?

any ideas ?
Thank you

**Comment by jeppewalther** [comment]
Try to have a look at the corresponding IR image. My guess is that the sensor is blinding itself. In my setup I have completely covered one of the three IR lamps. This makes it possibly to move the sensor closer to objects. Before blinding itself.

**Comment by Tabjones** [comment]
Here's the the corresponding depth colored images (from registration viewer)
![depth](https://cloud.githubusercontent.com/assets/1950251/7860422/102e348a-0549-11e5-8ea3-a6312a413f35.png)

I'm not sure what you mean by `blinding itself` !

**Comment by wiedemeyer** [comment]
If something is shiny/reflective, the light from the ir emitter can blind the ir sensor, because the reflected light is too strong.
To see this you should look at the ir image. `rosrun image_view image_view image:=/kinect2/ir/image`

**Comment by Tabjones** [comment]
Ok, now i understood, here's the ir images:
![screenshot from 2015-05-28 15 29 13](https://cloud.githubusercontent.com/assets/1950251/7861206/ff1da6c0-054e-11e5-8145-f1e3ad434ce7.png)

Covered one is just darker, but i don't see any artifacts in any of them, apart from that little shiny object in the top left corner, which i've no idea what it might be.

**Comment by jeppewalther** [comment]
Interesting i don't see any burnout issues. Edges on the  black device to the left seems more defined in image with a covered lens though. 

Out of curiosity.
what kind of tape are you using?. 
How close to objects can you get with it before you get burnout issues?.

**Comment by Tabjones** [comment]
This tape:
![20150603_155841](https://cloud.githubusercontent.com/assets/1950251/7962136/16552bf8-0a0c-11e5-9bee-870f796c60ff.jpg)

As you can see it is "semi transparent", we call it "paper-tape", but i have no idea how it might be called in other countries!

Anyway i also though of removing the external casing, like this:
![byijjognowooz3ao](https://cloud.githubusercontent.com/assets/1950251/7962215/7d316742-0a0c-11e5-9aad-c295db7a5ffb.jpg)

And see how the projector behaves.
I'll keep you posted if you are interested

**Comment by Tabjones** [comment]
I have removed the casing, but images and point clouds are much more noisier and burned out, so I put it back on! (Guess it was there for a reason!!!)

Anyway with the paper tape i can slightly come closer to objects before burning out, something like 35-40 cm, downside is that i can't see anything past 2 meters or maybe less.

**Comment by jeppewalther** [comment]
Thanks .. in danish it is malertape (Painters tape). I will give it at try .. So far my best results have been from a total blind off of one of the three lamps. 
![](http://share.jeppewalther.com/1433594959.88.jpg)

**Comment by Tabjones** [comment]
Oh cool! Thanks for sharing, i'll give it a try too
