### ISSUE TITLE
Wrong depth values

### ISSUE THREAD

**Issue by lakehanne** [code-iai/iai_kinect2#125]
Hi @wiedemeyer , I am picking up coordinates in the color frame from the viewer.cpp code and having to look up the depth equivalent in the depth map as follows:
```
            float depthIntensity = depth.at<float>(y, x);
```

but I notice the corresponding depth value I am picking up is a lot different from what the ground truth measurement should be. Picking up from the `dispDepth` doesn't help either. But when I pick the depth points from the depth map of libfreenect2's Protonect, it does yield sensible values.

(i) I notice Protonect's depth map  has a `min` and `max` value of `500` and `4500` respectively while the `min` and `max` values of the kinect2_bridge is between `1` and `12`. Why is there a difference in these values for the same depth camera? 

(ii) Also, the depth maps of Protonect seem a lot clearer than the one from kinect2_bridge. Why is this so? I would appreciate your reply.

**Comment by lakehanne** [comment]
Seems my problem is mostly from the way I am casting the depth values in ` float depthIntensity = depth.at<float>(y, x);`. After changing to  

```
unsigned short depthright  = depthDisp.at<unsigned short>(eye_y, eye_x)
```
 I seem to be obtaining the values of the depth pixel intensities. I am close but not there yet.

**Comment by wiedemeyer** [comment]
just use the depth image that is received by the callback method. It contains the depth values as uint16_t. Each pixels value is the depth in mm.

**Comment by lakehanne** [comment]
Thanks. This fixes my brobdinagian, unwanton quandary :)

**Comment by lakehanne** [comment]
It seems the retrieved depth values from the ros code and protonect are off by a significant margin. In protonect, I find the depth map on a stationary object to be accurate to within 5mm after accounting for the static offset of approx. 37mm from ground truth. In ROS, strangely, I found the values to flunctuate by an even wider margin post calibration. This was after adding the static offset from my calibrated values. These charts would explain my thoughts better.

![protonect_uncalibrated](https://cloud.githubusercontent.com/assets/8429860/8973005/76f885b4-3625-11e5-95b7-0012416fe6a3.jpg)

![ros_calibrated](https://cloud.githubusercontent.com/assets/8429860/8972996/5819c432-3625-11e5-9dda-66b82b1b0b75.jpg)

**Comment by wiedemeyer** [comment]
The offset is just an offset that is added to the depth values, it does not change the depth values in any other way, so it cannot be the source of fluctuation. Maybe the offset that is estimated is wrong, you could just change the value in the `calib_depth.yaml`. The whole depth offset is a preliminary part.

**Comment by lakehanne** [comment]
I was talking about the offset as a result of the incorrect tables of kinect2 libfreenect driver as discussed [here](https://github.com/OpenKinect/libfreenect2/issues/223).

**Comment by wiedemeyer** [comment]
The hard coded tables is solved.
