### ISSUE TITLE
Calibration problem: I can't get depth image 

### ISSUE THREAD

**Issue by Guhnoo** [code-iai/iai_kinect2#126]
Hello,  I have some problem in calibration. 

# I can run ' calibration record ir' like this
$ optirun --no-failsafe rosrun kinect2_calibration kinect2_calibration chess5x7x0.034 record ir

![record ir](https://cloud.githubusercontent.com/assets/13333380/8851273/6b71e8a2-3189-11e5-9c13-cec33bdd5ab6.png)

![rqt](https://cloud.githubusercontent.com/assets/13333380/8851373/0905b242-318a-11e5-8ba1-d312322b1f7f.png)

I can't get nothing about depth except ir window, and I was given black depth img.

![cal-data](https://cloud.githubusercontent.com/assets/13333380/8851229/0e6bb214-3189-11e5-9546-457fbeb64f0b.png)

Is it right? or I have problem??  
when I test  Protonect  (try: $ optirun --no-failsafe ./Protonect)  , I am given four image well. 

 'record sync ' is also same 

## kinect2_bridge info
beta@alpa:~$ optirun --no-failsafe rosrun kinect2_bridge kinect2_bridge depth_method:=opengl reg_method:=opencl
parameter:
        base_name: kinect2
           sensor: 
        fps_limit: -1
       calib_path: /home/beta/catkin_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: opengl
     depth_device: -1
       reg_method: default
       reg_devive: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 2
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4

[Freenect2Impl] enumerating devices...
[Freenect2Impl] 12 usb devices connected
[Freenect2Impl] found valid Kinect v2 @4:3 with serial 029754145047
[Freenect2Impl] found 1 devices
Kinect2 devices found: 
  0: 029754145047 (selected)
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] opened

starting kinect2

[Freenect2DeviceImpl] starting...
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41    2e2e2e2e2e2e2e2e2e2e2e2e432e2e41
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e
0x0020:  0a 21 33 55 ef 00 17 40 00 08 00 00 10 00 00 00    2e2133552e2e2e402e2e2e2e2e2e2e2e
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    2e2e2e2e2e2e2e2e2e2e802e2e2e2e2e
0x0040:  31 33 00 00 00 05 14 0d 47 4d 46 39 31 32 2e 31    31332e2e2e2e2e2e474d463931322e31
0x0050:  58 00 00 00 00 00 00 00 07 00 00 00                582e2e2e2e2e2e2e2e2e2e2e

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  01 26 00 00                                        2e262e2e

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  03 26 00 00                                        2e262e2e

[Freenect2DeviceImpl] enabling usb transfer submission...
[Freenect2DeviceImpl] submitting usb transfers...
[Freenect2DeviceImpl] started

device serial: 029754145047
device firmware: 4.3.3913.0.7
[Freenect2DeviceImpl] stopping...
[Freenect2DeviceImpl] disabling usb transfer submission...
[Freenect2DeviceImpl] canceling usb transfers...
[DepthPacketStreamParser::onDataReceived] not all subsequences received 0
[Freenect2DeviceImpl] stopped

default ir camera parameters: 
fx 365.82, fy 365.82, cx 261.954, cy 208.26
k1 0.0911889, k2 -0.271671, p1 0, p2 0, k3 0.0936603

default color camera parameters: 
fx 1081.37, fy 1081.37, cx 959.5, cy 539.5

camera parameters used:
camera matrix color:
[1133.923395373093, 0, 949.3852251462348;
  0, 1137.933434837629, 565.8910492688069;
  0, 0, 1]
distortion coefficients color:
[-0.2164195095026075, 6.731872045007637, -0.008686524459920842, -0.03039441404873483, -58.89171124284388]
camera matrix ir:
[2390.838493523019, 0, 255.7450083441651;
  0, 2229.278843545982, 211.6842679979474;
  0, 0, 1]
distortion coefficients ir:
[16.26194620894292, -2761.688219848951, 0.2450612211659857, -0.004496948418098325, -7.600562335179906]
rotation:
[0.9583645909446891, 0.002431295431940966, -0.2855370372227418;
  0.02268510740073345, 0.9961549079269922, 0.08462142350009744;
  0.2846448607047667, -0.08757561427411331, 0.9546244366549997]
translation:
[1.574080529774825; -0.4623861872280801; -4.385956440506297]
depth shift:
-13.3542

[DepthRegistration::New] Using CPU registration method!
[DepthRegistration::New] Using CPU registration method!
[kinect2_bridge] waiting for clients to connect

**Comment by wiedemeyer** [comment]
Hi,
those depth images have a 16 bit depth value. some programs might have problems to display them. Also the depth values are very low, so they might appear as black in viewers. You could simple `rostopic echo -n 1 /kinect2/sd/image_depth` and see if it contains just zeros, if not, everything is fine.

**Comment by Guhnoo** [comment]
Thank you for your answer.   when I run 
## $ roslaunch kinect2_bridge kinect2_bridge.launch publish_tf:=true 
and after
##  rostopic echo -n 1 /kinect2/sd/image_depth

I got this . 
![zero](https://cloud.githubusercontent.com/assets/13333380/9024876/b29ab46a-3923-11e5-957a-d5f58441792c.png)


and,.... Do I have problem?, doesn't it ?

**Comment by wiedemeyer** [comment]
For using OpenGL depth processor you need at least OpenGL version 3.3. Please check that. You can also try using OpenCL depth processor. Try out `./Protonect cl` from libfreenect2. And check the FAQ from the README.
