### ISSUE TITLE
Question- Kinect2_bridge interrupt driven or polling

### ISSUE THREAD

**Issue by cnanda-zbr** [code-iai/iai_kinect2#130]
Hi,
Had a simple question about the kinect2_bridge. Is the data transfer between libfreenect and kinect bridge interrupt driven or is it polled? Wanted to know what is basis for calculation of "nextFrame".

Best 
Chinmay

**Comment by wiedemeyer** [comment]
It is polled. See here: https://github.com/code-iai/iai_kinect2/blob/master/kinect2_bridge/src/kinect2_bridge.cpp#L924-L929

`nextFrame` is the timestamp for the next frame that should be published. After this timestamp is reached, `nextFrame` will be increased by `deltaT`, which is the time between two frames defined by the `fps_limit` parameter.
