### ISSUE TITLE
Install instruction breaks because of libfreenect2's changes

### ISSUE THREAD

**Issue by wkentaro** [code-iai/iai_kinect2#154]
About: https://github.com/code-iai/iai_kinect2#install

no `examples/protonect` in libfreenect2.
https://github.com/OpenKinect/libfreenect2/tree/master/examples

And header files are not found,
```
% mkdir build
% cd build
% cmake ../examples
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26")
-- checking for module 'glfw3'
--   found glfw3, version 3.0.4
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wkentaro/tech/libfreenect2/build
% make
Scanning dependencies of target Protonect
[ 33%] Building CXX object CMakeFiles/Protonect.dir/Protonect.cpp.o
/home/wkentaro/tech/libfreenect2/examples/Protonect.cpp:36:33: fatal error: libfreenect2/logger.h: No such file or directory
 #include <libfreenect2/logger.h>
                                 ^
compilation terminated.
make[2]: *** [CMakeFiles/Protonect.dir/Protonect.cpp.o] Error 1
make[1]: *** [CMakeFiles/Protonect.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by vishu2287** [comment]
which libfreenect2 you are using?

**Comment by wkentaro** [comment]
OpenKinect/libfreenect2

**Comment by vishu2287** [comment]
try to rebuild libfreenect2, 
$ <path to libfreenect2>/libfreenect2/examples/build
$ make clean
$ cmake ..
$ make
$ sudo make install

"sudo make install" makes the include folder available to all the packages

**Comment by wkentaro** [comment]
actually it fails at building for libfreenect2.
```
cd libfreenect2/examples
mkdir build
cd build
cmake ..
make  # This fails
sudo make install
```

**Comment by vishu2287** [comment]
can you check logger.h file in libfreenect2/examples/protonect/include/libfreenect2  is present?

**Comment by wkentaro** [comment]
it seems moved to include dir at root.
https://github.com/OpenKinect/libfreenect2/tree/master/include/libfreenect2

**Comment by JimmyDaSilva** [comment]
I was just facing the same issue right now.
I managed to compile and make it work for me.
It seems that the new way to make & install now is
```
cd libfreenect2
mkdir build
cmake .. #add -DENABLE_OPENCL or -DENABLE_OPENGL if you want to use your GPU
make 
sudo make install
```
Protonect executable is now in ```libfreenect2/build/bin```

**Comment by wkentaro** [comment]
Thanks!
That works and I can see all images by running ./Protonect.

However I have another problem described at here. #104

Anyway this issue has been fixed.

2015年9月28日月曜日、Jimmy DA SILVA<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:

> I was just facing the same issue right now.
> I managed to compile and make it work for me.
> It seems that the new way to make & install now is
>
> cd libfreenect2
> mkdir build
> cmake .. #add -DENABLE_OPENCL or -DENABLE_OPENGL if you want to use your GPU
> make
> sudo make install
>
> Protonect executable is now in libfreenect2/build/bin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-iai/iai_kinect2/issues/154#issuecomment-143696993>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by pallavbakshi** [comment]
Hi,

I installed the libfreenect2 on 11 Jan 2016 as per the instructions mentioned on the github page of libfreenect2. You can find two bin folders - one is in libfreenect2 and the other one inside of build. The Protonect example is inside the build -> bin. Just make sure to do - ./build/bin/Protonect

Thanks! Just trying to help
