### ISSUE TITLE
rgb image from kinect2_viewer( question ) 

### ISSUE THREAD

**Issue by cnanda-zbr** [code-iai/iai_kinect2#156]
Hi,

Is is possible to get a non-rectified rgb image from the kinect2_bridge ? Or do I have to subscribe to non-rectified topic from the bridge for that ? What is the best solution with minimum code change that I could do  ?

Best
Chinmay

**Comment by wiedemeyer** [comment]
It's not possible with the kinect2_viewer. But you could simply use `rosrun image_view image_view image:=/kinect2/hd/image_color`
