### ISSUE TITLE
could not detect the color chessboard when doing the calibration

### ISSUE THREAD

**Issue by summer1216** [code-iai/iai_kinect2#159]
![screenshot from 2015-10-01 00 41 54](https://cloud.githubusercontent.com/assets/12925865/10208733/b4720d84-67d5-11e5-944f-df5ee813372a.png)
![screenshot from 2015-10-01 00 42 15](https://cloud.githubusercontent.com/assets/12925865/10208734/b472b2e8-67d5-11e5-8fc9-554fee4be4a9.png)

Hello, as you can see from the images, I could only do the calibration for the ir camera, but for rgb camera the chessboard can not be detected. I think it's strange.. What could be the reason? Thanks if you could answer this!

**Comment by wiedemeyer** [comment]
Which commands did you execute and what is the terminal output? Did you tried to rotate the pattern and place it in different distances and positions? I need some more input to help.
