### ISSUE TITLE
kinect2_bridge can't find libGLEWmx.so.1.11

### ISSUE THREAD

**Issue by Julse** [code-iai/iai_kinect2#16]
Hello,

when I try to run kinect2_bridge I get the following error:

`error while loading shared libraries: libGLEWmx.so.1.11: cannot open shared object file: No such file or directory`

I compiled libfreenect2 with CpuDepthRegistration and Protonect works fine. 
I'm running on Intel i7 with Ubuntu 14.04 and ROS Indigo.

Do I have to link the library manually?

**Comment by RoboEvangelist** [comment]
I was getting the aformentioned error, but now I get this. I wonder if this has something to do with and update/upgrade I did after I installed the kinect repository and libfreekinect2 driver:



[Freenect2Impl] enumerating devices...
[Freenect2Impl] 12 usb devices connected
[Freenect2Impl] failed to open Kinect v2 @4:1!
[Freenect2Impl] found 0 devices
[Freenect2Impl] requested device 0 is not connected!
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 12 usb devices connected
[Freenect2Impl] failed to open Kinect v2 @4:1!
[Freenect2Impl] found 0 devices
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 12 usb devices connected
[Freenect2Impl] failed to open Kinect v2 @4:1!
[Freenect2Impl] found 0 devices
[Freenect2Impl] requested device 0 is not connected!
Error opening device #1
OpenCV Error: Assertion failed (!fixedSize() || ((Mat*)obj)->size.operator()() == _sz) in create, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp, line 1364
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp:1364: error: (-215) !fixedSize() || ((Mat*)obj)->size.operator()() == _sz in function create

**Comment by RoboEvangelist** [comment]
it seems to be a permission issue, because when I run the libfreenect examples, I have to do it with 'sudo' in front
