### ISSUE TITLE
Flashing black screen after calibration

### ISSUE THREAD

**Issue by renxinhe** [code-iai/iai_kinect2#163]
Hello,
I've recently calibrated the Kinect sensor with the checker board pattern. When I look at the output from kinect2_viewer, however, the screen is constantly flashing black. I've attached some screenshots. I've also noticed that when the viewer is black, the RGB topic outputs a bunch of zeros, and the viewer fps shots to above 100, compared to 20 fps when there is a crisp image. Is it possible that the amount of data is too high for the computer to handle? kinect2_bridge is also flooding the output with
>[OpenCLDepthPacketProcessor] avg. time: 0ms -> ~infHz
[DepthRegistrationOpenCL::registerDepth] ERROR: clEnqueueWriteBuffer(-5)
[DepthRegistrationOpenCL::registerDepth] ERROR: clEnqueueWriteBuffer(-5)
[DepthRegistrationOpenCL::registerDepth] ERROR: clEnqueueWriteBuffer(-5)
...

Is there a way to fix this?

Thanks,
Jim

![screenshot from 2015-09-22 19 53 15](https://cloud.githubusercontent.com/assets/8283781/10358368/732cf9d4-6d42-11e5-85b5-3497eb77c4c0.png)
![screenshot from 2015-09-22 19 53 22](https://cloud.githubusercontent.com/assets/8283781/10358367/732cbee2-6d42-11e5-97e4-bc75f6db6440.png)

**Comment by wiedemeyer** [comment]
I don't know. I never experienced anything like that before. Since it's an OpenCL error, maybe it is related to the GPU. What GPU are you using. What is the CPU usage while running kinect2_bridge and the viewer?
Try to run kinect2_bridge and then subscribe to a topic with `rostopic hz /kinect2/hd/image_depth_rect`. Do the errors show up too?

**Comment by renxinhe** [comment]
The laptop is running on NVIDIA® GTX 860M. It has built-in Intel HD graphics.

I've ran the kinect2_bridge, and here is a screenshot of the output:
![image](https://cloud.githubusercontent.com/assets/8283781/10500360/7975f850-728c-11e5-8014-3e473b6d7cf7.png)

It doesn't seem to generate any error.

**Comment by wiedemeyer** [comment]
It's probably related to the opencl errors, if it is not running correctly, the depth image is wrong to.
The `-5` means `CL_OUT_OF_RESOURCES`, maybe running the cloud viewer and the kinect2_bridge is using to much VRAM, or there are also some other applications using the GPU. I don't know how to solve this issue, maybe it helps to use a newer nvidia driver, or by closing windows that are not needed, or don't use point cloud viewer and use `rosrun kinect2_viewer kinect2_viewer ... -image` instead.
One other thing that looks wrong is `... avg. time: 0ms` So there is something wrong with the measurement in libfreenect2.

**Comment by wiedemeyer** [comment]
Hi, I updated the OpenCL code. Could you pull the lastest changes and check again?
