### ISSUE TITLE
Offset after calibration

### ISSUE THREAD

**Issue by GeHagit** [code-iai/iai_kinect2#172]
Hi, I have calibrated the kinect twice now, step by step as described. I still get this mismatch. Why does the kinect displaces the arm so much?
![bildschirmfoto vom 2015-10-28 11 01 24](https://cloud.githubusercontent.com/assets/5082403/10785574/4d260c0c-7d65-11e5-8be2-2d87ec1775e0.png)

![calibration_results](https://cloud.githubusercontent.com/assets/5082403/10785852/f7a00038-7d66-11e5-8200-f5f39d188791.png)
These are the results of my calibration. Did something go wrong?

![bildschirmfoto vom 2015-10-28 11 22 33](https://cloud.githubusercontent.com/assets/5082403/10785894/40022518-7d67-11e5-9ec6-82f06eb8d9f5.png)
I also wanted to ask what the "error 0.532786" indicates. It is the result of the ir calibration. What information can I get from the camera matrix and the distortion coefficients regarding the calibration?

**Comment by wiedemeyer** [comment]
Hi,
the error number is the reprojetion error. https://en.wikipedia.org/wiki/Reprojection_error
The lower the number, the better. Really good results are probably below 0.2 on color, ir and sync.

I can't really see the mismatch on the arm, but I can clearly see it on the walls, roof, etc. The overlayed depth does not match the color. What is the re-projection error of the color and the sync calibration?
