### ISSUE TITLE
ERROR: clEnqueueReadBuffer kinect2_bridge crashes randomly

### ISSUE THREAD

**Issue by ankitbhatia** [code-iai/iai_kinect2#174]
Sometimes the kinect2_bridge randomly quits sending back messages. The error triggered is: 

[OpenCLDepthPacketProcessor::run] ERROR: clEnqueueReadBuffer (-57)
terminate called after throwing an instance of 'cl::Error'
  what():  clEnqueueReadBuffer

Any ideas if this can be fixed?

**Comment by wiedemeyer** [comment]
That comes from the libfreenect2 OpenCL code. `-57` means `CL_INVALID_EVENT_WAIT_LIST`: if event_wait_list is NULL and num_events_in_wait_list greater than 0, or event_wait_list is not NULL and num_events_in_wait_list is 0, or if event objects in event_wait_list are not valid events.
So there is something wrong with the events. Could you open an issue on libfreenect2 GitHub. And include information on what GPU, driver version, you are using.
