### ISSUE TITLE
Calibration pattern not recognized in IR

### ISSUE THREAD

**Issue by hgaiser** [code-iai/iai_kinect2#175]
I am trying to perform the calibration procedure but the calibration pattern is not detected in the IR image. I tried playing with the IR ranges but I can't seem to get anything reasonable. The room I am in has windows, but there is no direct sunlight present so I doubt this is the issue.

![Calibration in IR image](http://s21.postimg.org/8nfat0fyv/calibration_ir.png)

Does anyone have some tips?

**Comment by wiedemeyer** [comment]
Did you used a ink printer? Than it's maybe the same as #80.

**Comment by hgaiser** [comment]
This was indeed the issue, printing it on a laser printer helped a lot! Thanks :)
