### ISSUE TITLE
How to subscribe a frame in opencv with Kinect2 bridge?

### ISSUE THREAD

**Issue by shamoorti** [code-iai/iai_kinect2#176]
Hey Thiemo,
I wanted to know how to subscribe a frame in opencv with Kinect2 bridge. Is it already done in bride? I read somewhere that I can use image_transport library. Can you explain how to add the dependencies? Or is it a good way to do it?
Thanks in advance :)

**Comment by wiedemeyer** [comment]
Hi,
you might want to look at the tutorials:
http://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28c%2B%2B%29
http://wiki.ros.org/cv_bridge/Tutorials/UsingCvBridgeToConvertBetweenROSImagesAndOpenCVImages http://wiki.ros.org/image_transport/Tutorials/SubscribingToImages
