### ISSUE TITLE
Strange values from depth map!

### ISSUE THREAD

**Issue by shamoorti** [code-iai/iai_kinect2#188]
Hello guys,
As you know I am working on a robotic project which I find and object in RGB image (x,y values) and send it to depth map to find the representative value in depth which is the distance to the object. But I get to much offset. In this picture you can see the cup being found in matlab and the red star in the middle of the cup is the point which I want to find the distance to it hence the distance to object. But as I send it to depth map it like depth = double(depth(x,y) or using impixel(depth, x ,y) I get wrong values. In the case of this picture the distance shows 1.65 meters which the actual value is  1 meter exact. I subscribe :
Kinect = rossubscriber('/kinect2/hd/image_mono');
Depth = rossubscriber('/kinect2/hd/image_depth_rect');  
Then I receive the them fine but the depth value is wrong.

![kinectcup](https://cloud.githubusercontent.com/assets/10776933/11502087/0bdad482-9839-11e5-8a92-4a31c21eb7b9.png)

Anyone has any idea what's wrong? By the way Rviz shows the perfect cloud but faced to the ground like this. Is this tf problem or just like this is ok?
![rviz](https://cloud.githubusercontent.com/assets/10776933/11502061/e9bfc196-9838-11e5-95bc-34053c954068.png)
?

**Comment by wiedemeyer** [comment]
On default z is pointing up in RViz. You could use a static TF publisher to provide a transform for the TF link of the Kinect2.
I don't know what `impixel` or the other does. But the depth values are stored in mm, so it would be `depth(y, x) / 1000.0` to get the measurement in meters. On the other hand taking just one point is a bad idea, better take the average or median of a region around the point you are looking for.

**Comment by wiedemeyer** [comment]
And your should also use `mono_rect` together with the `depth_rect`, else the image coordinates won't match between the images.

**Comment by shamoorti** [comment]
Thanks a lot Thiemo for the good tip. Also look at this point cloud from rviz. It seems cup is so shifted back in depth. Still camera is not calibrated I think.
![shifteddepth](https://cloud.githubusercontent.com/assets/10776933/11502906/daee99c6-983d-11e5-9472-05050c8c85b5.png)

**Comment by shamoorti** [comment]
Yeah there was definitely calibration problems which is fixed now. Also thank Thiemo for the good advice about the centre point. You can close this thread.
