### ISSUE TITLE
Image Transformation of /qhd/image_rgb_rect to /sd/image_rgb_rect?

### ISSUE THREAD

**Issue by filipetrocadoferreira** [code-iai/iai_kinect2#190]
What is the transformation between /qhd/ and /sd/ color image? And why is there depth information on the sd topic?

**Comment by wiedemeyer** [comment]
SD in the frame of the ir sensor and QHD/HD is the the rgb sensor frame. The transform is the one, that gets calculated during the calibration.
Why shouldn't there be a depth in SD?

**Comment by filipetrocadoferreira** [comment]
I meant in the sd/image_color.
