### ISSUE TITLE
Build error DepthPacketProcessor is now internal

### ISSUE THREAD

**Issue by lamogui** [code-iai/iai_kinect2#191]
Hi
the project doesn't build anymore due to recent changes in libfreenect2.
I opened an libfreenect2 issue here: [https://github.com/OpenKinect/libfreenect2/issues/496]

The build error is 
```
kinect2_bridge.cpp:393:5: error: incomplete type ‘libfreenect2::DepthPacketProcessor’ used in nested name specifier
     libfreenect2::DepthPacketProcessor::Config config;
```

I use ROS jade.

**Comment by xlz** [comment]
See #189.

**Comment by lamogui** [comment]
Ok thanks

**Comment by wiedemeyer** [comment]
PR Merged.
