### ISSUE TITLE
Building iai_kinect2 - error: ‘_mm_mfence’ was not declared in this scope

### ISSUE THREAD

**Issue by metropt** [code-iai/iai_kinect2#192]
What should I do to solve it?

```
make[2]: *** Waiting for unfinished jobs....
In file included from /home/followinspiration/rosws/src/iai_kinect2/kinect2_registration/src/depth_registration_opencl.cpp:28:0:
/usr/include/CL/cl.hpp: In function ‘void cl::detail::fence()’:
/usr/include/CL/cl.hpp:1041:38: error: ‘_mm_mfence’ was not declared in this scope
     inline void fence() { _mm_mfence(); }
                                      ^
```

BTW Protonect is working.
My PC:
- Ubuntu 14.04
- 4 GB Ram
- Inter Core i3-3220 CPU
- GeForce GT 610/PCIe/SSE2
- 32-bit

**Comment by wiedemeyer** [comment]
It is a problem of the OpenCL header, not really a problem of this package. Here you can find the solution https://github.com/OpenKinect/libfreenect2/issues/355, you have to enable SSE.
