### ISSUE TITLE
How to calculate the X and Y real world coordinates

### ISSUE THREAD

**Issue by shamoorti** [code-iai/iai_kinect2#193]
Hey Thiemo,
I was wondering about this topic How to calculate the X and Y real world coordinates with the bridge. I know I can use cloud points but just subscribing to it cost a lot CPU usage. So I just want to calculate with the simple formula like this:
%% Calculating cartesian coordinates
 %Camera RGB intrinsic paramters
       fx_rgbcam = 1059.9465578241038;
       fy_rgbcam = 1053.9326808799726;
       cx_rgbcam = 954.8832667758844;
       cy_rgbcam = 523.7385829106058;

% create convinient matrices for the coordinate calculation
yv = y - cy_rgbcam;                                 
xv = x - cx_rgbcam;

%Calculate the actual coordinates in space (3D points)
  yObj = (yv * depth) / fy_rgbcam;
  xObj = (xv * depth) / fx_rgbcam;
But the values really seems wrong. The camera is calibrated maybe not perfectly but I get the exact distance from the object but not even close to the values of real world. Can you tell me what I'm doing wrong? Topics I use for getting the x and y from camera is image_mono_rect and for depth is image depth rect both in HD. Thanks in advance.

**Comment by wiedemeyer** [comment]
Hi,
you could look into the code of the [kinct2_viewer::createCloud](https://github.com/code-iai/iai_kinect2/blob/master/kinect2_viewer/src/viewer.cpp#L433-L466) and [kinct2_viewer::createLookup](https://github.com/code-iai/iai_kinect2/blob/master/kinect2_viewer/src/viewer.cpp#L490-L511). That code calculates the real world coordinates from the depth image.
