### ISSUE TITLE
Flat surfaces appear curved - is this normal?

### ISSUE THREAD

**Issue by mriem** [code-iai/iai_kinect2#198]
Hello, 

I started using the kinect one a week ago and found this great package in ROS which really eased the process for me. Thanks!

Anyway, I have done a calibration as described in the git hub page and I got back some results which seem to make sense, i.e., they are in the same order of magnitude as the examples in the kinect2_bridge/data.

The problem I have is that flat surfaces such as walls appear curved. Before this kinect one, I used and Asus Xtion and this effect was not so noticeable. I want to know if you people also have noticed this (or if I am doing something wrong).

To be honest, the curving effect is also visible when I run kinect2_bridge without the calibration (default values), but I thought the calibration should somehow try to compensate for this.

Attached are some images which show what I am talking about.

Just an update: The curved areas seem to be always coincident with the borders of the image. 
 
Thanks in advance for your help.

![screenshot from 2015-12-28 14 49 38](https://cloud.githubusercontent.com/assets/2963767/12020654/a176120c-ad76-11e5-9a06-26c395e08f9d.png)
![screenshot from 2015-12-28 14 49 55](https://cloud.githubusercontent.com/assets/2963767/12020656/a1782d08-ad76-11e5-9c4d-ee7fff509581.png)
![screenshot from 2015-12-28 14 50 12](https://cloud.githubusercontent.com/assets/2963767/12020655/a177fd92-ad76-11e5-97a5-43311f65dfd9.png)
![screenshot from 2015-12-28 14 50 24](https://cloud.githubusercontent.com/assets/2963767/12020657/a17dd0f0-ad76-11e5-9e51-79f13b0b592b.png)

Miguel Oliveira

**Comment by vishu2287** [comment]
@mriem , You need to calibrate kinect2 
https://github.com/code-iai/iai_kinect2/tree/master/kinect2_calibration#calibrating-the-kinect-one

**Comment by miguelriemoliveira** [comment]
Hi Vishu,

Thanks for the feedback.

I had already done the calibration as described in the git hub page. I use around 150 RGB, IR and Sync images. Still, I get these curved surfaces. 

Any other ideas? Could it be that the calibration is wrong / not optimal?

Thanks, Miguel

**Comment by wiedemeyer** [comment]
I think it's a general problem of ToF sensors and has nothing to do with the calibration. See issue #121.

**Comment by mriem** [comment]
Hello,

Thanks for the repply. I saw issue #121 as you suggested.

There is just one thing that does not make sense to me:  if its a problem with the ToF, then why does the curved effect appear greater near the borders of the image? 

Take a look at this image. The camera is placed almost parallel to the right wall plane, at about 20 cm from it. Still, the curved effect appears to be greater in the ceiling (which is close to the borders of the image)

![screenshot from 2015-12-29 18 29 21](https://cloud.githubusercontent.com/assets/2963767/12039658/1d473166-ae5a-11e5-9dfc-d356c4ad3ea8.png)

Anyway, I am closing this issue since its clearly not a kinect2_bridge problem (also occurs in the kinect2 sdk). 

Miguel
