### ISSUE TITLE
hd/points, qhd/points, and sd/points not published

### ISSUE THREAD

**Issue by rshanor** [code-iai/iai_kinect2#204]
I start the kinect2 by running: rosrun kinect2_bridge kinect2_bridge _depth_method:=opengl _reg_method:=cpu

I can view the output fine using: rosrun kinect2_viewer kinect2_viewer sd cloud

However, I am trying to view and eventually use this data as a point cloud. However, the point cloud topics are not published. The full output of rostopic list is as follows:

/kinect2/hd/camera_info
/kinect2/hd/image_color
/kinect2/hd/image_color/compressed
/kinect2/hd/image_color_rect
/kinect2/hd/image_color_rect/compressed
/kinect2/hd/image_depth_rect
/kinect2/hd/image_depth_rect/compressed
/kinect2/hd/image_mono
/kinect2/hd/image_mono/compressed
/kinect2/hd/image_mono_rect
/kinect2/hd/image_mono_rect/compressed
/kinect2/qhd/camera_info
/kinect2/qhd/image_color
/kinect2/qhd/image_color/compressed
/kinect2/qhd/image_color_rect
/kinect2/qhd/image_color_rect/compressed
/kinect2/qhd/image_depth_rect
/kinect2/qhd/image_depth_rect/compressed
/kinect2/qhd/image_mono
/kinect2/qhd/image_mono/compressed
/kinect2/qhd/image_mono_rect
/kinect2/qhd/image_mono_rect/compressed
/kinect2/sd/camera_info
/kinect2/sd/image_color_rect
/kinect2/sd/image_color_rect/compressed
/kinect2/sd/image_depth
/kinect2/sd/image_depth/compressed
/kinect2/sd/image_depth_rect
/kinect2/sd/image_depth_rect/compressed
/kinect2/sd/image_ir
/kinect2/sd/image_ir/compressed
/kinect2/sd/image_ir_rect
/kinect2/sd/image_ir_rect/compressed
/rosout
/rosout_agg

**Comment by wiedemeyer** [comment]
Hi,
point clouds are only published when the launch file is launched. `roslaunch kinect2_bridge kinect2_bridge.launch`
