### ISSUE TITLE
Can I output data points to a text file? What file should/can be edited?

### ISSUE THREAD

**Issue by hyderjake** [code-iai/iai_kinect2#210]

**Comment by wiedemeyer** [comment]
Yes, you can output points to a text file, you just have to implement it. Alternatively, if you want to store whole point cloud you can use PCL for it.

**Comment by JimmyDaSilva** [comment]
@hyderjake I recommend you use PCL to save the pointcloud as a .pcd file.
Instructions here:
http://pointclouds.org/documentation/tutorials/writing_pcd.php
