### ISSUE TITLE
could not find a package configuration file provided by "freenect2"

### ISSUE THREAD

**Issue by zmartycc** [code-iai/iai_kinect2#231]
After  the command
**catkin_make -DCMAKE_BUILD_TYPE="Release"**
，there was a error:
**CMake Error at iai_kinect2/kinect2_bridge/CMakeLists.txt:22 (find_package):
  By not providing "Findfreenect2.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "freenect2", but CMake did not find one.
  Could not find a package configuration file provided by "freenect2" with
  any of the following names:

    freenect2Config.cmake
    freenect2-config.cmake**.
I don't know how to fix it. Can anyone help me?

**Comment by wiedemeyer** [comment]
try to install libfreenect2.

**Comment by zmartycc** [comment]
I had installed libfreenect2 as the instructions. I used Kinect for windows v1 and the command ./bin/Protonect didn't work. The output message said no device connected.  Nothing else seemed wrong.

**Comment by wiedemeyer** [comment]
And did you do `make install` in libfreenect2? What path did you installed it to?
BTW: It will only work with Kinect v2.

**Comment by zmartycc** [comment]
I  did **make install** in **libfreenect2/depends/build**, and **/build** was a new file created followed the instructions.

**Comment by wiedemeyer** [comment]
Where did `make install` installed the files to? What is the output on the terminal?

**Comment by xlz** [comment]
For iai_kinect2, `catkin_make -DCMAKE_BUILD_TYPE="Release" -Dfreenect2_DIR=$HOME/freenect2`, this is what I have been doing.

**Comment by wiedemeyer** [comment]
Fixed it in fa55624ea7074ad66693582f53defb05ab14564b. `{HOME}/freenect2` is now one of the paths where it searches for libfreenect2.

**Comment by caozhenn** [comment]
you should install freenect in your XX_ws instead of home, some tutorials are wrong, try another tutorials.
