### ISSUE TITLE
Could not detect the device

### ISSUE THREAD

**Issue by zfxw0206** [code-iai/iai_kinect2#238]
I am using ROS Ubuntu14.04 to run the kinect. But some times, when I restart the computer, I could not detect the kinect. I need to manually remove the USB or restart the computer again, then it works. 

Does anybody have a idea about this? Thank you!

**Comment by wiedemeyer** [comment]
It is not really an issue of iai_kinect2. I would guess its related to your hardware, drivers or kernel, but I am not an expert in that.

**Comment by zfxw0206** [comment]
Ok, thank you!
