### ISSUE TITLE
registration_viewer -both broken on OS X

### ISSUE THREAD

**Issue by jmtatsch** [code-iai/iai_kinect2#24]
Hi Thiemo,

`rosrun registration_viewer viewer -kinect2 -both` crashes for me now with the attached errorlog. `rosrun registration_viewer viewer -kinect2 -image` or `rosrun registration_viewer viewer -kinect2  -cloud` on their own work fine. Its not too important to fix it, probably not too difficult either :)
                                                                                                                      
topic color: /kinect2_head/rgb_lowres/image
topic depth: /kinect2_head/depth_lowres/image
starting receiver...
_RegisterApplication(), FAILED TO REGISTER PROCESS WITH CPS/CoreGraphics in WindowServer, err=-50
2014-12-09 16:55:34.209 viewer[51411:418188] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
2014-12-09 16:55:34.212 viewer[51411:418188] *** Assertion failure in -[NSApplication init], /SourceCache/AppKit/AppKit-1343.16/AppKit.subproj/NSApplication.m:1720
2014-12-09 16:55:34.272 viewer[51411:418188] An uncaught exception was raised
2014-12-09 16:55:34.273 viewer[51411:418188] Creating more than one Application
2014-12-09 16:55:34.273 viewer[51411:418188] (
	0   CoreFoundation                      0x00007fff8cfb264c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8d1f46de objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8cfb242a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff9137e5b9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fff82d113f6 -[NSApplication init] + 131
	5   AppKit                              0x00007fff82d1119f +[NSApplication sharedApplication] + 138
	6   libvtkRendering.5.10.dylib          0x00000001075c04bb _ZN20vtkCocoaRenderWindow13CreateAWindowEv + 101
	7   libvtkRendering.5.10.dylib          0x00000001075c0e71 _ZN20vtkCocoaRenderWindow10InitializeEv + 191
	8   libvtkRendering.5.10.dylib          0x00000001075becd0 _ZN20vtkCocoaRenderWindow5StartEv + 18
	9   libvtkRendering.5.10.dylib          0x00000001075bcb32 _ZN30vtkCocoaRenderWindowInteractor10InitializeEv + 56
	10  libpcl_visualization.1.8.dylib      0x000000010d01f599 _ZN3pcl13visualization13PCLVisualizer16createInteractorEv + 213
	11  libpcl_visualization.1.8.dylib      0x000000010d01f342 _ZN3pcl13visualization13PCLVisualizerC2ERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEb + 838
	12  viewer                              0x00000001043675c6 _ZN8Receiver11cloudViewerEv + 358
	13  viewer                              0x0000000104361a38 _ZN8Receiver5startENS_4ModeE + 3960
	14  viewer                              0x000000010435e0ac main + 1468
	15  libdyld.dylib                       0x00007fff89d7f5c9 start + 1
	16  ???                                 0x0000000000000003 0x0 + 3
)
2014-12-09 16:55:34.273 viewer[51411:418188] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Creating more than one Application'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8cfb264c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8d1f46de objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8cfb242a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff9137e5b9 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fff82d113f6 -[NSApplication init] + 131
	5   AppKit                              0x00007fff82d1119f +[NSApplication sharedApplication] + 138
	6   libvtkRendering.5.10.dylib          0x00000001075c04bb _ZN20vtkCocoaRenderWindow13CreateAWindowEv + 101
	7   libvtkRendering.5.10.dylib          0x00000001075c0e71 _ZN20vtkCocoaRenderWindow10InitializeEv + 191
	8   libvtkRendering.5.10.dylib          0x00000001075becd0 _ZN20vtkCocoaRenderWindow5StartEv + 18
	9   libvtkRendering.5.10.dylib          0x00000001075bcb32 _ZN30vtkCocoaRenderWindowInteractor10InitializeEv + 56
	10  libpcl_visualization.1.8.dylib      0x000000010d01f599 _ZN3pcl13visualization13PCLVisualizer16createInteractorEv + 213
	11  libpcl_visualization.1.8.dylib      0x000000010d01f342 _ZN3pcl13visualization13PCLVisualizerC2ERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEb + 838
	12  viewer                              0x00000001043675c6 _ZN8Receiver11cloudViewerEv + 358
	13  viewer                              0x0000000104361a38 _ZN8Receiver5startENS_4ModeE + 3960
	14  viewer                              0x000000010435e0ac main + 1468
	15  libdyld.dylib                       0x00007fff89d7f5c9 start + 1
	16  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    51411 abort      rosrun registration_viewer viewer -kinect2 -both

**Comment by wiedemeyer** [comment]
I guess so. So what you can do is to run the viewer two times in parallel, once with `-image` and once with `-cloud`. So the `-both` is probably a wont-fix on OS X Yosemite.
