### ISSUE TITLE
Running libfreenect 2 on Intel NUC

### ISSUE THREAD

**Issue by pnambiar** [code-iai/iai_kinect2#259]
I'm trying to run kinect v2 with ROS. As a first step, I'm trying to run libfreenect 2 on Intel NUC -NUC5i7RYH with ubuntu Ubuntu 14.04.4 LTS.
I was able to install it successfully. However ./Protonect gives me the following error
Version: 0.2.0
Environment variables: LOGFILE=<protonect.log>
Usage: ./Protonect [-gpu=<id>] [gl | cl | cuda | cpu] [<device serial>]
        [-noviewer] [-norgb | -nodepth] [-help] [-version]
        [-frames <number of frames to process>]
To pause and unpause: pkill -USR1 Protonect
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 10 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @3:3 with serial 503931742542
[Info] [Freenect2Impl] found 1 devices
[Error] [OpenGLDepthPacketProcessorImpl] GLFW error 65544 X11: RandR gamma ramp support seems broken
[Error] [OpenGLDepthPacketProcessorImpl] GLFW error 65543 The requested client API version is unavailable
[Error] [OpenGLDepthPacketProcessor] Failed to create opengl window.

Any leads will be highly appreciated

**Comment by wiedemeyer** [comment]
Hi, did you followed [the instructions](https://github.com/OpenKinect/libfreenect2#linux)? Did you downloaded the debs for trusty with `libfreenect2/depends/download_debs_trusty.sh` and installed them?

**Comment by pnambiar** [comment]
Yes

**Comment by wiedemeyer** [comment]
you already have the same issue opened at libfreenect2, lets continue there and close this one.
