### ISSUE TITLE
sensor calibration

### ISSUE THREAD

**Issue by pnambiar** [code-iai/iai_kinect2#266]
I'm following the instructions you provided for Kinect calibration
https://github.com/code-iai/iai_kinect2/blob/master/kinect2_calibration/README.md

I have the forrowing running
1) roscore
2) rosrun kinect2_bridge kinect2_bridge _fps_limit:=2
3) rosrun kinect2_calibration kinect2_calibration chess5x7x0.03 record color 

I get the following error message, but I'm able to save the images
[ERROR] Tried to advertise a service that is already advertised in this node [/kinect2_calib_1461090415983227522/compressed/set_parameters]
[ERROR] Tried to advertise a service that is already advertised in this node [/kinect2_calib_1461090415983227522/compressed/set_parameters]

should I just ignore the error messages?

**Comment by wiedemeyer** [comment]
just ignore it
