### ISSUE TITLE
Installation Problem after cloning

### ISSUE THREAD

**Issue by zardchim** [code-iai/iai_kinect2#27]
Hi!

I have installed all the dependencies required, but after I cloned the repository to my catkin workspace, errors appears when I am using catkin_make, any idea to solve it? Thank you >.<

"/home/m2/catkin_ws/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:96:3: error: ‘FrameMap’ in namespace ‘libfreenect2’ does not name a type
   libfreenect2::FrameMap frames;
   ^
/home/m2/catkin_ws/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp: In member function ‘bool Kinect2Bridge::init(const string&, const string&)’:
/home/m2/catkin_ws/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:197:16: error: ‘create’ is not a member of ‘libfreenect2::FrameListener’
     listener = libfreenect2::FrameListener::create(libfreenect2::Frame::Color | libfreenect2::Frame::Ir | libfreenect2::Frame::Depth);
                ^
/home/m2/catkin_ws/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp: In member function ‘void Kinect2Bridge::run()’:
/home/m2/catkin_ws/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:379:17: error: ‘class libfreenect2::FrameListener’ has no member named ‘waitForNewFrame’
       listener->waitForNewFrame(frames);
                 ^
/home/m2/catkin_ws/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:379:33: error: ‘frames’ was not declared in this scope
       listener->waitForNewFrame(frames);
                                 ^
/home/m2/catkin_ws/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:392:17: error: ‘class libfreenect2::FrameListener’ has no member named ‘release’
       listener->release(frames);
                 ^
make[2]: *** [iai_kinect2/kinect2_bridge/CMakeFiles/kinect2_bridge.dir/src/kinect2_bridge.cpp.o] Error 1
make[1]: *** [iai_kinect2/kinect2_bridge/CMakeFiles/kinect2_bridge.dir/all] Error 2
make: *** [all] Error 2
Invoking "make" failed"

**Comment by airduke** [comment]
I also had the same error. I believe there is an error in the ubuntu instructions on https://github.com/wiedemeyer/libfreenect2. Step 1 is to clone: git clone https://github.com/OpenKinect/libfreenect2.git and should be as stated above.

**Comment by wiedemeyer** [comment]
That are the instructions for libfreenect2 from OpenKinect, therefore it is right. My one is just a fork of the OpenKinect one, so that I can make pull requests and supply modified versions to the users of iai_kinect2. I will not change any readme instructions. I hope libfreenect2 is soon in a shape that additional modifications are not needed anymore and that the original libfreenect2 repo can be used directly.

**Comment by Raffa87** [comment]
Hi, 
I have downloaded resource from https://github.com/wiedemeyer/libfreenect2 but I have the same problem on compliation

**Comment by wiedemeyer** [comment]
Please use https://github.com/OpenKinect/libfreenect2.
