### ISSUE TITLE
no chessboard seen on ir-image

### ISSUE THREAD

**Issue by royalheadwear** [code-iai/iai_kinect2#272]
Hi,
I followed the instructions for calibrating the kinect2 sensor.

The recording of colorimages worked fine, but when I tried to take a picture in the ir-mode the chessboard was not detected (added a screenshot) . Is it possible, that this happens because I didn't print it with an laser printer?

![bildschirmfoto vom 2016-05-03 11 14 03](https://cloud.githubusercontent.com/assets/19154381/14979082/6cdaf18a-1120-11e6-8b27-83439f1ee3e8.png)

**Comment by arminkazim7** [comment]
maybe its too far away have you tried moving the board a little closer?

**Comment by royalheadwear** [comment]
Okay... Thanks to the issue #80 I found out, that it actually was the ink printed Pattern. I printed it with a laser printer now and now its far better!!!
