### ISSUE TITLE
Publishing a Point Cloud Topic?

### ISSUE THREAD

**Issue by stefie10** [code-iai/iai_kinect2#28]
Hi --

Thanks for writing the Kinect 2 driver.  I'm wondering if the driver publishes a point cloud topic, so we can view the points in RVIZ? 

I found this package which converts it to PCL:
https://github.com/giacomodabisias/libfreenect2pclgrabber so I think it would be something like, convert the cloud to PCL and then publish a PountCloud2 topic for both the low and highres camera streams:  http://docs.ros.org/api/sensor_msgs/html/msg/PointCloud2.html

Stefanie

**Comment by wiedemeyer** [comment]
I added the nodes for publishing to the launch file

**Comment by andreykurenkov** [comment]
Hi,
I know that this is a closed issue, but I am looking into subscribing to the point cloud topic and am not sure if I am doing something wrong or if there is a problem. When I run the kinect2_bridge, if I do rostopic list I do not see the points topics but only the image topics for depth:
/kinect2/depth_highres/image
/kinect2/depth_highres/image/compressedDepth
/kinect2/depth_lowres/camera_info
/kinect2/depth_lowres/image
/kinect2/depth_lowres/image/compressedDepth
/kinect2/depth_rect/camera_info
/kinect2/depth_rect/image
/kinect2/depth_rect/image/compressedDepth

I am trying to use the point cloud for SLAM, but just cannot understand why it is not published. Do I neet to set some paramter for the points topics to be published, or is there something wrong?

**Comment by wiedemeyer** [comment]
Point clouds are created by image_proc. Those nodes are only started with the launch file. You have to launch the launch file instead of directly running the node.

**Comment by andreykurenkov** [comment]
Ah, thank you - though it is fairly obvious I did not think of it after
always using rosrun with kinect2_bridge.

On Sun, Mar 22, 2015 at 4:54 AM, Thiemo Wiedemeyer <notifications@github.com
