### ISSUE TITLE
Hello when i try to compile i get this error is it possible to disable OpenCL?

### ISSUE THREAD

**Issue by arminkazim7** [code-iai/iai_kinect2#280]
home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_opencl.cpp:33:21: fatal error: CL/cl.hpp: Datei oder Verzeichnis nicht gefunden
compilation terminated.
iai_kinect2/kinect2_registration/CMakeFiles/kinect2_registration.dir/build.make:100: recipe for target 'iai_kinect2/kinect2_registration/CMakeFiles/kinect2_registration.dir/src/depth_registration_opencl.cpp.o' failed
make[2]: *** [iai_kinect2/kinect2_registration/CMakeFiles/kinect2_registration.dir/src/depth_registration_opencl.cpp.o] Error 1
In file included from /usr/include/eigen3/Eigen/Core:276:0,
                 from /usr/include/eigen3/Eigen/Geometry:4,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.h:22,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.cpp:18:
/usr/include/eigen3/Eigen/src/Core/Functors.h:973:28: warning: ‘template<class _Operation> class std::binder2nd’ is deprecated [-Wdeprecated-declarations]
 struct functor_traits<std::binder2nd<T> >
                            ^
In file included from /usr/include/c++/5/bits/stl_function.h:1128:0,
                 from /usr/include/c++/5/string:48,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/sstream:38,
                 from /usr/include/c++/5/complex:45,
                 from /usr/include/eigen3/Eigen/Core:28,
                 from /usr/include/eigen3/Eigen/Geometry:4,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.h:22,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.cpp:18:
/usr/include/c++/5/backward/binders.h:143:11: note: declared here
     class binder2nd
           ^
In file included from /usr/include/eigen3/Eigen/Core:276:0,
                 from /usr/include/eigen3/Eigen/Geometry:4,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.h:22,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.cpp:18:
/usr/include/eigen3/Eigen/src/Core/Functors.h:977:28: warning: ‘template<class _Operation> class std::binder1st’ is deprecated [-Wdeprecated-declarations]
 struct functor_traits<std::binder1st<T> >
                            ^
In file included from /usr/include/c++/5/bits/stl_function.h:1128:0,
                 from /usr/include/c++/5/string:48,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/sstream:38,
                 from /usr/include/c++/5/complex:45,
                 from /usr/include/eigen3/Eigen/Core:28,
                 from /usr/include/eigen3/Eigen/Geometry:4,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.h:22,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.cpp:18:
/usr/include/c++/5/backward/binders.h:108:11: note: declared here
     class binder1st
           ^
In file included from /usr/include/eigen3/Eigen/Core:276:0,
                 from /usr/include/eigen3/Eigen/Geometry:4,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.h:22,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/kinect2_registration.cpp:22:
/usr/include/eigen3/Eigen/src/Core/Functors.h:973:28: warning: ‘template<class _Operation> class std::binder2nd’ is deprecated [-Wdeprecated-declarations]
 struct functor_traits<std::binder2nd<T> >
                            ^
In file included from /usr/include/c++/5/bits/stl_function.h:1128:0,
                 from /usr/include/c++/5/string:48,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/core.hpp:56,
                 from /usr/local/include/opencv2/opencv.hpp:47,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/include/kinect2_registration/kinect2_registration.h:24,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/kinect2_registration.cpp:18:
/usr/include/c++/5/backward/binders.h:143:11: note: declared here
     class binder2nd
           ^
In file included from /usr/include/eigen3/Eigen/Core:276:0,
                 from /usr/include/eigen3/Eigen/Geometry:4,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.h:22,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/kinect2_registration.cpp:22:
/usr/include/eigen3/Eigen/src/Core/Functors.h:977:28: warning: ‘template<class _Operation> class std::binder1st’ is deprecated [-Wdeprecated-declarations]
 struct functor_traits<std::binder1st<T> >
                            ^
In file included from /usr/include/c++/5/bits/stl_function.h:1128:0,
                 from /usr/include/c++/5/string:48,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/core.hpp:56,
                 from /usr/local/include/opencv2/opencv.hpp:47,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/include/kinect2_registration/kinect2_registration.h:24,
                 from /home/linaro/cat/src/iai_kinect2/kinect2_registration/src/kinect2_registration.cpp:18:
/usr/include/c++/5/backward/binders.h:108:11: note: declared here
     class binder1st
           ^
CMakeFiles/Makefile2:398: recipe for target 'iai_kinect2/kinect2_registration/CMakeFiles/kinect2_registration.dir/all' failed
make[1]: *** [iai_kinect2/kinect2_registration/CMakeFiles/kinect2_registration.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by wiedemeyer** [comment]
It is disabled if OpenCL is not installed, but you can disable it manually. But I would recommend trying to solve your OpenCL problems instead.
