### ISSUE TITLE
Depth processing rate

### ISSUE THREAD

**Issue by pnambiar** [code-iai/iai_kinect2#282]
Question: Why is the depth processing rate much higher than the rate at which the depth data is streamed?
[ INFO] [1463598900.157176270]: [Kinect2Bridge::main] depth processing: ~5.61417ms (~178.121Hz) publishing rate: ~29.96Hz
[ INFO] [1463598900.157258055]: [Kinect2Bridge::main] color processing: ~18.9041ms (~52.8985Hz) publishing rate: ~30.2929Hz

**Comment by wiedemeyer** [comment]
One shows how fast the data is processed and the other one shows how often it is published. Even if you computer needs 6 ms to process each frame, it cannot publish more frames than it receives from the sensor, which is transmitting at 30 Hz.
