### ISSUE TITLE
how to convert point cloud data into pcd file ? 

### ISSUE THREAD

**Issue by nomi321** [code-iai/iai_kinect2#286]
i want to convert point cloud data into pcd file. how can i do this ?

**Comment by wiedemeyer** [comment]
[This should do the job.](http://lmgtfy.com/?q=ros+point+cloud+to+pcd)

**Comment by nomi321** [comment]
bro i tried this already. but it converts a point cloud to multiple pcd files. is this correct or m making any mistake ? m sorry if my question made u laugh ... does all pcd files represnt that cloud ?

**Comment by wiedemeyer** [comment]
From the [documentation](http://wiki.ros.org/pcl_ros#pcd_to_pointcloud) of `pointcloud_to_pcd`:
"Subscribes to a ROS topic and saves point cloud messages to PCD files. Each message is saved to a separate file, names are composed of an optional prefix parameter, the ROS time of the message, and the .pcd extension."
PCD: http://pointclouds.org/documentation/tutorials/pcd_file_format.php

**Comment by nomi321** [comment]
ok thanks bro ...
