### ISSUE TITLE
3D coordinates of a an object

### ISSUE THREAD

**Issue by adarshmodh** [code-iai/iai_kinect2#291]
Hello @wiedemeyer I am very new to this #271 and have successfully interfaced the kinect2 with ros using your repository, but i have a similar problem. I have already visualized images and 3D point clouds using various packages like rqt, rviz and image_view and so everything seems to be working fine. But now I want to find out the 3D co-ordinates of specific points in a point cloud (mostly of the centroid of some particular object). So can I know how to find out the real world 3D co-ordinates (in metres) of such a centroid (say taking kinect as the reference frame and also origin). And then also the 16-bit depth values corresponding to the same points. Thanks in advance.

**Comment by wiedemeyer** [comment]
Those question got answered a couple of times already. Please search in the closed issues for answers first.
The coordinates of a point from a point cloud are the x, y, z values stored in that point, they are stored in meters and the reference frame is the sensor. Each point x_i, y_i (2D image coordinates) corresponds to pixel with the same coordinates in color or depth image of the same size.
