### ISSUE TITLE
Using Kinect2 for turtlebot_follower etc.. ?

### ISSUE THREAD

**Issue by jesst17** [code-iai/iai_kinect2#293]
14.04
Indigo
rosrun kinect2_viewer kinect2_viewer kinect2 sd cloud working well
Hey guys! 
We download  and install iai_kinect2 so i want to use kinect2 camera sensor for different things (such as turtlebot_follower or  tutorials at learn.turtlebot.com [which written for only  kinect1]  ) but turtlebot_follower give me   "No devices connected.... waiting for devices to be connected" (after  roslaunch kinect2_bridge kinect2_bridge.launch)
I thought that problem is about Using KinectV2, is there any way to solve this issue, or Am i doing something wrong or miss something ??

**Comment by wiedemeyer** [comment]
Hi,
if you have any problems related to using iai_kinect2, then this is the right place. But if you have issues using other packages, please contact the maintainers of those packages.
