### ISSUE TITLE
kinect2_calibration: command line arguments

### ISSUE THREAD

**Issue by awhampton** [code-iai/iai_kinect2#312]
Is the -path flag handled correctly?

At line 1289, it is:

`else if(arg == "-path" && argI + 1 < argc)`

Should it instead be something like:

`else if(arg == "-path" && ++argI < argc)`

**Comment by wiedemeyer** [comment]
True, I will fix it. Thanks.

**Comment by awhampton** [comment]
Just to make it easier, I created a pull request with the above change. I also fixed another typo.

This is a great package. Thanks for all your work!
