### ISSUE TITLE
tf_publish:= true

### ISSUE THREAD

**Issue by anthonio4990** [code-iai/iai_kinect2#313]
hi, 

i tried to run: roslaunch kinect2_bridge kinect2_bridge.launch publish_tf:=true

but then, i got this  message:
[kinect2-2] process has died [pid 24982, exit code 127, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=kinect2 __log:=/home/anthonio/.ros/log/d070d1d6-5029-11e6-92b5-408d5c55f0c6/kinect2-2.log].
log file: /home/anthonio/.ros/log/d070d1d6-5029-11e6-92b5-408d5c55f0c6/kinect2-2*.log

i thought that,  it wasn't  an actual error, since there are so many topics still published. 
But then i run: rosrun rviz rviz. and cannot find the tf-topic that i was expecting. is there something i have missed?

 Thanks !

**Comment by wiedemeyer** [comment]
try to run `rosrun kinect2_bridge kinect2_bridge _publish_tf:=true`.
