### ISSUE TITLE
Only 2Hz depth image throughput...  what frame rates are typical and possible?

### ISSUE THREAD

**Issue by CrumResearch** [code-iai/iai_kinect2#316]
Using iai_kinect2 on a Mac Mini running Ubuntu 16.04 with its Intel GPU hardware, I am only able to record hd depth images to ROS .bag files around 2 Hz.  How about you?  Are you able to see and bag much faster frame rates?  I certainly want to achieve 30 Hz if possible and need to find the performance bottleneck in my system.  Thanks for any suggestions.

**Comment by wiedemeyer** [comment]
2 Hz sounds really slow. If you just run the kinect2_bridge and `rostopic hz /kinect2/hd/image_depth_rect`, how high is the frame rate you are receiving? This is probably the maximum cou can get, based on your hardware. The next bottleneck could be your hard drive, with `rostopic bw /kinect2/hd/image_depth_rect` you could check how much bandwidth is needed.
For recording data, I would recommend to use the the compressed topics, if the CPU is not the bottleneck. Compression reduces the bandwidth a lot, but will increase the CPU load.
