### ISSUE TITLE
include  libfreenect2/libfreenect2.hpp not found

### ISSUE THREAD

**Issue by christiankerl** [code-iai/iai_kinect2#32]
the freenect2Config.cmake generated by libfreenect2 upstream `make install` sets freenect2_INCLUDE_DIR to `$CMAKE_INSTALL_PREFIX/include/libfreenect2`. However, kinect2_bridge.cpp expects freenect2_INCLUDE_DIR to be `$CMAKE_INSTALL_PREFIX/include/` leading to compilation error. 

I guess we should fix this in libfreenect2?

**Comment by wiedemeyer** [comment]
Right, good idea. I never had an issue with this because I always install libfreenect2 to a path where the `include` folder is in the default search paths for header files.

**Comment by wiedemeyer** [comment]
I think this has been fixed in libfreenect2
