### ISSUE TITLE
Kinect2 - calibration distance

### ISSUE THREAD

**Issue by roliveiradoteu** [code-iai/iai_kinect2#321]
Trying to calibrate my kinect but found the squares are extremely difficult to find beyond say 2.5 meters, specially in the IR camera. 

I have tried the 9x6 25mm and custom size 5x7 42mm, using a sheet of glass. I am very confident on how flat it is and in the quality of the print :|

What are the distances you used? 

`

> SYNC:
> [ INFO] [main] starting calibration...
> [ INFO] [CameraCalibration::calibrateExtrinsics] Camera Matrix Color:
> [1049.063297223599, 0, 970.1703855809652;
>   0, 1051.376671809587, 541.3998374124549;
>   0, 0, 1]
> [ INFO] [CameraCalibration::calibrateExtrinsics] Distortion Coeeficients Color:
> [0.0425717854236773, -0.05445630548076841, -0.001224311957900713, 0.002418917668647387, 0.01296968051534258]
> 
> [ INFO] [CameraCalibration::calibrateExtrinsics] Camera Matrix Ir:
> [363.1207484380441, 0, 255.3945939804648;
>   0, 363.8227411415941, 201.1685640910512;
>   0, 0, 1]
> [ INFO] [CameraCalibration::calibrateExtrinsics] Distortion Coeeficients Ir:
> [0.106888412418272, -0.3046707328905076, -0.0007651680338693838, 0.0001973448401870654, 0.1197836435797597]
> 
> [ INFO] [CameraCalibration::calibrateExtrinsics] calibrating Color and Ir extrinsics...
> [ INFO] [CameraCalibration::calibrateExtrinsics] re-projection error: 8.29465

`

Big re-projection errors in the sync part but individually I got 0.13 and 0.12 for Color and IR...

Cheers

//ro

**Comment by roliveiradoteu** [comment]
Is it possible to redo just the sync step, considering the position will be different (I moved the camera)? 

What puzzles me is that the colour image is 16x9 and the ir is 4x3 meaning there is a substancial part of the colour image that is not covered by the chessboard, during this step i mean.

**Comment by wiedemeyer** [comment]
I usually used distances between 0.6 and 2.5 meters, near, middle and far. To go further away, you need a larger board, but then you can not be as close.
The individual calibrations are looking fine. For the extrinsics, it is important that the sensor and the board **do not move** at all, because the images are not taken at the same time. Holding on of them in a hand is not working well.
Yes you can remove all `*_sync_*` files and record new ones.
The color image is much wider and the depth image is higher, but there is an overlapping part in the center area. In the images at https://github.com/code-iai/iai_kinect2#screenshots you should see where the overlap is. For the sync calibration you have to place the board so that it is detected on both images, so that both windows are showing the colored detection overlay.

**Comment by roliveiradoteu** [comment]
Thanks Thiemo.
I redid the calibration using more extreme angles and got around 0.21 px, I wasn't tilting the calibration pattern by the required amount for good geometry to be detected. 

Regards,

**Comment by roliveiradoteu** [comment]
@wiedemeyer 

The coloured depth image shows a black strip in the upper part, is this in indication of poor calibration ?

It is noticeable as well that the size of this black edge is greater in the sd image, but appears similar in both the qhd and hd images. 

<a href="http://en.zimagez.com/zimage/screenshot-180217-154716.php" target="_blank" title="black strip"><img src="http://en.zimagez.com/miniature/screenshot-180217-154716.png" alt="black strip" /></a>

<a href="http://en.zimagez.com/zimage/screenshot-180217-155416.php" target="_blank" title="zoom"><img src="http://en.zimagez.com/miniature/screenshot-180217-155416.png" alt="zoom" /></a>

**Comment by wiedemeyer** [comment]
It could come from the rectification: https://github.com/code-iai/iai_kinect2#screenshots
There you can see a black pixels at the border of the color image. And because the depth image has a different aspect ratio there are valid depth pixels for those black pixels.

**Comment by roliveiradoteu** [comment]
@wiedemeyer Given your statement in > https://github.com/code-iai/iai_kinect2/issues/349#issuecomment-270887609 does it make sense to use only the IR and RGD and pose calibration information? This would mean not using the calib_depth.yaml?

**Comment by wiedemeyer** [comment]
The depth calibration has nothing to do with the black areas at top and bottom.

**Comment by roliveiradoteu** [comment]
yes i appreciate that is due to the rectification. 

i am just wondering if I can use the default depth calibration and still use the intrinsic and extrinsic information from iai_kinect2.

**Comment by wiedemeyer** [comment]
Yes you can. Just set the value in that file to 0.
