### ISSUE TITLE
Malloc Errors when trying to calibrate

### ISSUE THREAD

**Issue by vkee** [code-iai/iai_kinect2#322]
Hi,

When I run **rosrun kinect2_bridge kinect2_bridge _fps_limit:=2**, **rosrun kinect2_calibration kinect2_calibration chess5x7x0.03 record color** or anything with rosrun for that matter, I get 

malloc: unknown:0: assertion botched
free: called with unallocated block argument
last command: (null)

I have no problems running **roslaunch kinect2_bridge kinect2_bridge.launch**. I tried reinstalling everything but still have the same problem.

**Comment by wiedemeyer** [comment]
I guess your system is misconfigured. Which OS/ROS version are you using? Are you using OpenCV 3?
