### ISSUE TITLE
kinect2 calibration distance measurement

### ISSUE THREAD

**Issue by cnanda-zbr** [code-iai/iai_kinect2#324]
Hi Thiemo,
So on the description for calibration you mention that .
"I did some tests on the measured and the computed distance based on the detected chess board. It seems like the Kinect2 (or at least the Kinect2s I am using) has a static offset of around 24 mm."

Did you measure distance from front of the lens or from the back plane of the camera( if there is a way to get to it)  ? 

-Best 
Chinmay

**Comment by wiedemeyer** [comment]
Hi,
with *measured* I meant the distances returned by the sensor and *computed* are the distances to the plane defined by the chessboard corners.
