### ISSUE TITLE
Problem with launching kinect2_bridge

### ISSUE THREAD

**Issue by maximest-pierre** [code-iai/iai_kinect2#329]
I got a problem with launching the kinect2_bridge under ros-indigo. I can use the protonect interface to show an image.
## rosrun

rosrun kinect2_bridge kinect2_bridge  
/home/mst-pierre/sara_ws/devel/lib/kinect2_bridge/kinect2_bridge: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/mst-pierre/sara_ws/devel/lib/libkinect2_registration.so)
/home/mst-pierre/sara_ws/devel/lib/kinect2_bridge/kinect2_bridge: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/mst-pierre/sara_ws/devel/lib/libkinect2_registration.so)
/home/mst-pierre/sara_ws/devel/lib/kinect2_bridge/kinect2_bridge: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/mst-pierre/freenect2/lib/libfreenect2.so.0.2)
/home/mst-pierre/sara_ws/devel/lib/kinect2_bridge/kinect2_bridge: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /home/mst-pierre/freenect2/lib/libfreenect2.so.0.2)
[ INFO] [Kinect2Bridge::initialize] parameter:
        base_name: kinect2
           sensor: default
        fps_limit: -1
       calib_path: /home/mst-pierre/sara_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: cuda
     depth_device: -1
       reg_method: opencl
       reg_device: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 2
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4
[Info] [CudaDepthPacketProcessorImpl] device 0: Quadro M2000 @ 1162MHz Memory 4035MB
[Info] [CudaDepthPacketProcessorImpl] selected device 0
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 7 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:3 with serial 004429261047
[Info] [Freenect2Impl] found 1 devices
[ INFO] [Kinect2Bridge::initDevice] Kinect2 devices found: 
[ INFO] [Kinect2Bridge::initDevice]   0: 004429261047 (selected)
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 20_16384 ir: 60_8*33792
[Info] [Freenect2DeviceImpl] opened
[ INFO] [Kinect2Bridge::initDevice] starting kinect2
[Info] [Freenect2DeviceImpl] starting...
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
[ INFO] [Kinect2Bridge::initDevice] device serial: 004429261047
[ INFO] [Kinect2Bridge::initDevice] device firmware: 2.3.3913.0
[Info] [Freenect2DeviceImpl] stopping...
[Info] [Freenect2DeviceImpl] canceling rgb transfers...
[Info] [Freenect2DeviceImpl] canceling depth transfers...
[Info] [Freenect2DeviceImpl] stopped
[ WARN] [Kinect2Bridge::initCalibration] using sensor defaults for color intrinsic parameters.
[ WARN] [Kinect2Bridge::initCalibration] using sensor defaults for ir intrinsic parameters.
[ WARN] [Kinect2Bridge::initCalibration] using defaults for rotation and translation.
[ WARN] [Kinect2Bridge::initCalibration] using defaults for depth shift.
[ INFO] [DepthRegistration::New] Using OpenCL registration method!
[ INFO] [DepthRegistration::New] Using OpenCL registration method!
[1]    4547 segmentation fault (core dumped)  rosrun kinect2_bridge kinect2_bridge
## roslaunch

─$ roslaunch kinect2_bridge kinect2_bridge.launch                        139 ↵
... logging to /home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/roslaunch-wm-log-4636.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://wm-log:32975/
# SUMMARY

PARAMETERS
- /kinect2_bridge/base_name: kinect2
- /kinect2_bridge/base_name_tf: kinect2
- /kinect2_bridge/bilateral_filter: True
- /kinect2_bridge/calib_path: /home/mst-pierre/...
- /kinect2_bridge/depth_device: -1
- /kinect2_bridge/depth_method: default
- /kinect2_bridge/edge_aware_filter: True
- /kinect2_bridge/fps_limit: -1.0
- /kinect2_bridge/jpeg_quality: 90
- /kinect2_bridge/max_depth: 12.0
- /kinect2_bridge/min_depth: 0.1
- /kinect2_bridge/png_level: 1
- /kinect2_bridge/publish_tf: False
- /kinect2_bridge/queue_size: 5
- /kinect2_bridge/reg_device: -1
- /kinect2_bridge/reg_method: default
- /kinect2_bridge/sensor: 
- /kinect2_bridge/use_png: False
- /kinect2_bridge/worker_threads: 4
- /kinect2_points_xyzrgb_hd/queue_size: 5
- /kinect2_points_xyzrgb_qhd/queue_size: 5
- /kinect2_points_xyzrgb_sd/queue_size: 5
- /rosdistro: indigo
- /rosversion: 1.11.20

NODES
  /
    kinect2 (nodelet/nodelet)
    kinect2_bridge (nodelet/nodelet)
    kinect2_points_xyzrgb_hd (nodelet/nodelet)
    kinect2_points_xyzrgb_qhd (nodelet/nodelet)
    kinect2_points_xyzrgb_sd (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[kinect2-1]: started with pid [4654]
process[kinect2_bridge-2]: started with pid [4655]
process[kinect2_points_xyzrgb_sd-3]: started with pid [4656]
process[kinect2_points_xyzrgb_qhd-4]: started with pid [4657]
process[kinect2_points_xyzrgb_hd-5]: started with pid [4658]
[ INFO] [1477512853.872771633]: Loading nodelet /kinect2_bridge of type kinect2_bridge/kinect2_bridge_nodelet to manager kinect2 with the following remappings:
[ INFO] [1477512853.877449325]: waitForService: Service [/kinect2/load_nodelet] could not connect to host [wm-log:59140], waiting...
[ INFO] [1477512853.890926883]: Initializing nodelet with 4 worker threads.
[ INFO] [1477512853.898999126]: waitForService: Service [/kinect2/load_nodelet] is now available.
[ INFO] [1477512853.961261246]: [Kinect2Bridge::initialize] parameter:
        base_name: kinect2
           sensor: default
        fps_limit: -1
       calib_path: /home/mst-pierre/sara_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: default
     depth_device: -1
       reg_method: default
       reg_device: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 5
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4
[Info] [CudaDepthPacketProcessorImpl] device 0: Quadro M2000 @ 1162MHz Memory 4035MB
[Info] [CudaDepthPacketProcessorImpl] selected device 0
[Info] [Freenect2Impl] enumerating devices...
[Info] [Freenect2Impl] 7 usb devices connected
[Info] [Freenect2Impl] found valid Kinect v2 @2:3 with serial 004429261047
[Info] [Freenect2Impl] found 1 devices
[ INFO] [1477512854.103149178]: [Kinect2Bridge::initDevice] Kinect2 devices found: 
[ INFO] [1477512854.103217589]: [Kinect2Bridge::initDevice]   0: 004429261047 (selected)
[Info] [Freenect2DeviceImpl] opening...
[Info] [Freenect2DeviceImpl] transfer pool sizes rgb: 20_16384 ir: 60_8_33792
[Info] [Freenect2DeviceImpl] opened
[ INFO] [1477512854.197890282]: [Kinect2Bridge::initDevice] starting kinect2
[Info] [Freenect2DeviceImpl] starting...
[Info] [Freenect2DeviceImpl] submitting rgb transfers...
[Info] [Freenect2DeviceImpl] submitting depth transfers...
[Info] [Freenect2DeviceImpl] started
[ INFO] [1477512854.564461628]: [Kinect2Bridge::initDevice] device serial: 004429261047
[ INFO] [1477512854.564529698]: [Kinect2Bridge::initDevice] device firmware: 2.3.3913.0
[Info] [Freenect2DeviceImpl] stopping...
[Info] [Freenect2DeviceImpl] canceling rgb transfers...
[Info] [Freenect2DeviceImpl] canceling depth transfers...
[Info] [Freenect2DeviceImpl] stopped
[ WARN] [1477512854.785453932]: [Kinect2Bridge::initCalibration] using sensor defaults for color intrinsic parameters.
[ WARN] [1477512854.785527253]: [Kinect2Bridge::initCalibration] using sensor defaults for ir intrinsic parameters.
[ WARN] [1477512854.785565349]: [Kinect2Bridge::initCalibration] using defaults for rotation and translation.
[ WARN] [1477512854.785632884]: [Kinect2Bridge::initCalibration] using defaults for depth shift.
[ INFO] [1477512854.860149299]: [DepthRegistration::New] Using OpenCL registration method!
[ INFO] [1477512854.860189756]: [DepthRegistration::New] Using OpenCL registration method!
[FATAL] [1477512855.010252272]: Failed to load nodelet '/kinect2_points_xyzrgb_hd`of type`depth_image_proc/point_cloud_xyzrgb`to manager`kinect2'
[FATAL] [1477512855.010433988]: Failed to load nodelet '/kinect2_points_xyzrgb_sd`of type`depth_image_proc/point_cloud_xyzrgb`to manager`kinect2'
[FATAL] [1477512855.010498220]: Failed to load nodelet '/kinect2_points_xyzrgb_qhd`of type`depth_image_proc/point_cloud_xyzrgb`to manager`kinect2'
[FATAL] [1477512855.010586179]: Failed to load nodelet '/kinect2_bridge`of type`kinect2_bridge/kinect2_bridge_nodelet`to manager`kinect2'
[kinect2-1] process has died [pid 4654, exit code -11, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=kinect2 __log:=/home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/kinect2-1.log].
log file: /home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/kinect2-1_.log
[kinect2_bridge-2] process has died [pid 4655, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load kinect2_bridge/kinect2_bridge_nodelet kinect2 __name:=kinect2_bridge __log:=/home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/kinect2_bridge-2.log].
log file: /home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/kinect2_bridge-2_.log
[kinect2_points_xyzrgb_sd-3] process has died [pid 4656, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb kinect2 rgb/camera_info:=kinect2/sd/camera_info rgb/image_rect_color:=kinect2/sd/image_color_rect depth_registered/image_rect:=kinect2/sd/image_depth_rect depth_registered/points:=kinect2/sd/points __name:=kinect2_points_xyzrgb_sd __log:=/home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/kinect2_points_xyzrgb_sd-3.log].
log file: /home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/kinect2_points_xyzrgb_sd-3_.log
[kinect2_points_xyzrgb_qhd-4] process has died [pid 4657, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb kinect2 rgb/camera_info:=kinect2/qhd/camera_info rgb/image_rect_color:=kinect2/qhd/image_color_rect depth_registered/image_rect:=kinect2/qhd/image_depth_rect depth_registered/points:=kinect2/qhd/points __name:=kinect2_points_xyzrgb_qhd __log:=/home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/kinect2_points_xyzrgb_qhd-4.log].
log file: /home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/kinect2_points_xyzrgb_qhd-4_.log
[kinect2_points_xyzrgb_hd-5] process has died [pid 4658, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb kinect2 rgb/camera_info:=kinect2/hd/camera_info rgb/image_rect_color:=kinect2/hd/image_color_rect depth_registered/image_rect:=kinect2/hd/image_depth_rect depth_registered/points:=kinect2/hd/points __name:=kinect2_points_xyzrgb_hd __log:=/home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/kinect2_points_xyzrgb_hd-5.log].
log file: /home/mst-pierre/.ros/log/410fbb86-9bb7-11e6-9d94-1866da424f22/kinect2_points_xyzrgb_hd-5_.log
[kinect2_bridge-2] restarting process
process[kinect2_bridge-2]: started with pid [4801]
[kinect2_points_xyzrgb_sd-3] restarting process
process[kinect2_points_xyzrgb_sd-3]: started with pid [4802]
[kinect2_points_xyzrgb_qhd-4] restarting process
process[kinect2_points_xyzrgb_qhd-4]: started with pid [4803]
[kinect2_points_xyzrgb_hd-5] restarting process
process[kinect2_points_xyzrgb_hd-5]: started with pid [4804]
[ INFO] [1477512855.282892226]: Loading nodelet /kinect2_bridge of type kinect2_bridge/kinect2_bridge_nodelet to manager kinect2 with the following remappings:
[ INFO] [1477512855.288499209]: waitForService: Service [/kinect2/load_nodelet] could not connect to host [wm-log:40394], waiting...
^C[kinect2_points_xyzrgb_hd-5] killing on exit
[kinect2_points_xyzrgb_qhd-4] killing on exit
[kinect2_points_xyzrgb_sd-3] killing on exit
[kinect2_bridge-2] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by wiedemeyer** [comment]
Hi,
please compile it in Debug, run it in `gdb` and paste the stack trace here, so that I can see, why it is crashing.
