### ISSUE TITLE
Problem with ROS distribution

### ISSUE THREAD

**Issue by jackj012** [code-iai/iai_kinect2#330]
Hi everybody, i'm new to the ROS and need to use this package. i wonder if i can use it on the newest ROS Kinetic distribution?  also i'm running my ubuntu on virtual machine,  would that cause any problem when connecting kinect? thanks

**Comment by andre-nguyen** [comment]
I'm running it successfully on two different machines running Kinetic so yes it will work. Not sure about the VM thing but usually that works.

**Comment by wiedemeyer** [comment]
I think there could be issues with USB 3 and VMs. If I remember correctly some people had problems with it, please look at the issues at the libfreenect2 GitHub repository for more details.
