### ISSUE TITLE
iai_kinect2 use too much cpu loads

### ISSUE THREAD

**Issue by hzcipher** [code-iai/iai_kinect2#341]
I have a problem that iai_kinect2 use too much cpu loads. I have a nvidia GTX1070 gpu, but it only use  5% ,  which configuration should I use that put more computing tasks to the gpu?

**Comment by wiedemeyer** [comment]
Use OpenCL/CUDA for depth processing and if you have an Inter CPU with HD Graphics use VAAPI instead of TurboJPEG.
