### ISSUE TITLE
"image_color_rect"  zero values where depth is zero

### ISSUE THREAD

**Issue by ralpguler** [code-iai/iai_kinect2#342]
Hi,

Is it possible to obtain "image_color_rect" values that are non-zero in locations where no depth information is available?

I have tried calling the  libfreenect2/registration->apply function with enable_filter as 'False' but this didn't do it.

Thank you.

**Comment by wiedemeyer** [comment]
Hi,
there is a simple solution. Create a mask from the depth image and and set all color image pixel to black where the mask is zero.

**Comment by ralpguler** [comment]
@wiedemeyer, thank you for your reply.

Perhaps I was misunderstood. By default, the "image_color_rect"(SD) values are zero. I provide an example below(taken from https://github.com/code-iai/iai_kinect2/issues/173) 

What I am trying to do is to obtain non-zero values.

![](https://cloud.githubusercontent.com/assets/5452370/10794522/969b8a80-7d95-11e5-8136-522c22cd9160.png)

**Comment by wiedemeyer** [comment]
It needs depth information to know which SD color pixel belongs to which HD color pixel. Without depth, no mapping. You can only use the HD/QHD color and depth images if black pixels is a problem in your application.
