### ISSUE TITLE
roslaunch kinect2_bridge kinect2_bridge.launch requires the 'screen' arg to be set

### ISSUE THREAD

**Issue by letmejoin** [code-iai/iai_kinect2#344]
I use kinect2 in my notebook, but something wrong occurs. I don't know how to result it.
hehe@hehe-Lenovo-XiaoXin-V4000:~$ roslaunch kinect2_bridge kinect2_bridge.launch... logging to /home/hehe/.ros/log/a3eee9bc-c0e1-11e6-ac28-f0761caa79c3/roslaunch-hehe-Lenovo-XiaoXin-V4000-11592.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

**[/home/hehe/catkin_ws/src/iai_kinect2/kinect2_bridge/launch/kinect2_bridge.launch] requires the 'screen' arg to be set
The traceback for the exception was written to the log file**

**Comment by wiedemeyer** [comment]
Sorry, that was an issue of the last PR that I merged. It should be fixed now.
