### ISSUE TITLE
Calibration of Kinect v2

### ISSUE THREAD

**Issue by srinimd2005** [code-iai/iai_kinect2#349]
I tried the calibration procedure mentioned in the documentation, but I am curious to know whether I should add the color and ir calibration files in kinect2_bridge package beform I perform the rosrun kinect2_calibration kinect2_calibration chessboard5x7x0.03 record sync and the perform the calibrate process or I should do without them. 

Does the calibration needs to be done repeatedly to achieve efficient calibration because I have performed calibration of Kinect camera three times using 5x7x0.03 to achieve this calibration
![calibration_meas_vs_computed_distance](https://cloud.githubusercontent.com/assets/19781123/21589934/5148fd9e-d0f7-11e6-8a8b-3980f222d384.png)

**Comment by wiedemeyer** [comment]
you should do the calibration with the uncalibrated state of the sensor. And you only have to calibrate it once. The depth calibration itself is only preliminary code, it might not improve results at all.
