### ISSUE TITLE
Where can I learn the algorithm

### ISSUE THREAD

**Issue by XeMinZa** [code-iai/iai_kinect2#353]
well,I got the parameters of my kinect2 and the result from visualization is ok! But I don't want to use ROS and how can I realize it with C++. 
## Only I want to do is using the parameter to transform my image. 
Where can I learn the algorithm in this part?  the source code is too complex for me to read. 
I use the libfreenect2 to receive my kinect2's data.And I know there is a registration part in the lib, however I don't know how to use it with the parameters which I got from iai_kinect2.

**Comment by wiedemeyer** [comment]
The registration method from libfreenect2 does not need those parameters, you can simply use it. And if you really want to understand the algorithm, then you need read the source code.

**Comment by XeMinZa** [comment]
@wiedemeyer thanks. I have completed my code. The registration is really simply to use.

**Comment by SunnZhang** [comment]
Hi, there! I got some issues about the registration method too, I wonder if you can help me.

**Comment by XeMinZa** [comment]
What is problem? I didn't use the iai to registrate the ir image with rgb image. What I used is the freenect2 API. That's really simple, and in my situation, it perform good enough for me.
