### ISSUE TITLE
Kinect2_bridge + libfreenect2-openni2

### ISSUE THREAD

**Issue by aaramirezd** [code-iai/iai_kinect2#361]
Hi Thiemo

I'm working on applications using kinect v2 with ROS and i always use your work that is excellent

Recently started with an application that uses Nite to extract skeleton,then,  my question is simple, is there any way to run kinect2_bridge  together with the driver libfreenect2-openni2?

Thanks,
Andrés

**Comment by wiedemeyer** [comment]
I don't know, but one Kinect2 can only be used by a single instance at a time. I think you need to modify libfreenect2, kinect2_bridge and the openni part to achieve it.

**Comment by mehmetkillioglu** [comment]
I'm working on a similar application. Is there any update on that subject?
