### ISSUE TITLE
synchronisation of >1 kinect2

### ISSUE THREAD

**Issue by TheTesla** [code-iai/iai_kinect2#363]
Is there a way to synchronize multiple kinect2? Maybe using a single shot photo function? It would be nice to have multiple perspectives at one exact point in time.

**Comment by wiedemeyer** [comment]
I don't know of any way to do this. Also if their field of view is overlapping it might cause interferences.

**Comment by mpatalberta** [comment]
No their is no way to coordinates multiple cameras. If they were sychronized the cameras will blind one another.
