### ISSUE TITLE
Calibration data path "" does not exist.

### ISSUE THREAD

**Issue by adilbonzi** [code-iai/iai_kinect2#366]
I have followed all the instructions as described on the [https://github.com/code-iai/iai_kinect2](page). My output when i launch roslaunch kinect2_bridge kinect2_bridge.launch publish_tf:=true, i am getting the error after it publishes some packets,  "RgbPacketStreamParser::handleNewData" skipping rgb packet!

By launching rtabmap, it is showing no mapping, no odometry, no point clouds and also rviz is not showing any mapping. 

But when i run my protonect, it is working perfectly.

I read the issue #52 and tried to reduce the frame rate. But when I run _rosrun kinect2_bridge kinect2_bridge _fps_limit:=1_, it gives me this error ,"**Calibration data path** "" does not exist.". 

Kindly advise me on this matter.

**Comment by wiedemeyer** [comment]
If you use the node, you have to add a underscore in front of the parameters `_fps_limit:=1`.
