### ISSUE TITLE
libopencv-dev rosdep definitions missing for Ubuntu 12.04 / Hydro?

### ISSUE THREAD

**Issue by brhemes** [code-iai/iai_kinect2#37]
I am working on getting this built on a setup with Ubuntu 12.04 with ROS Hydro and get the following error when running `rosdep install -r --from-paths .`
```
hemes@jake:~/ros_ws/src/iai_kinect2$ rosdep install -r --from-paths .
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
registration_viewer: No definition of [libopencv-dev] for OS version [precise]
kinect2_calibration: No definition of [libopencv-dev] for OS version [precise]
kinect2_bridge: No definition of [libopencv-dev] for OS version [precise]
depth_registration: No definition of [libopencv-dev] for OS version [precise]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```
After investigating a bit it seems that there were changes with where OpenCV lives from Hydro to Indigo and `libopencv-dev` is the rosdep key for Indigo.  Per the Indigo migration document (http://wiki.ros.org/indigo/Migration#OpenCV) I believe these dependencies should be replaced with `cv_bridge`.

After making the above change on my build, the error went away.

**Comment by wiedemeyer** [comment]
fixed in 670cd895e0d065b354291b8e95d598d1235d6a88. Thanks for reporting. As I am not using Hydro anymore I don't see this problems.
