### ISSUE TITLE
Points topic not displyed

### ISSUE THREAD

**Issue by mallela** [code-iai/iai_kinect2#373]
After I launch the kinect2_brigde node, I see all the topics published successfully except the following topics:
kinect2/sd/points
kinect2/qhd/points
kinect2/hd/points
Kindly note the above issue and provide me with a fix for the issue.

**Comment by wiedemeyer** [comment]
Hi,
you have to use the launch file instead. It starts the nodes responsible for publishing the point topics.

**Comment by mallela** [comment]
Thank! It works fine now.

-Praneeta
