### ISSUE TITLE
during the calibration, can the color and ir images  take at the same time?

### ISSUE THREAD

**Issue by EXing** [code-iai/iai_kinect2#378]
during the calibration, can the color and ir images  taken at the same time?
for the every set, taking 100 images seems hard without tripod!

**Comment by leoujz** [comment]
Can you detect checkerboard successfully on IR image?

**Comment by EXing** [comment]
yes!

**Comment by EXing** [comment]
@leoujz yes!!

**Comment by wiedemeyer** [comment]
No, they can not be taken at the exact same time. You can get good results without a tripod too, but it may be harder, or less good.

**Comment by JimmyDaSilva** [comment]
@wiedemeyer This I don't understand. As we take both depth and rgb during the sync calibration step, couldn't we :
- grab rgb and depth images at the same time
- calibrate rgb
- calibrate depth
- rectify previous rgb and depth
- calibrate sync 

I am just curious.

**Comment by wiedemeyer** [comment]
The problem is, that ir and color have different sizes. Ir has more height, while color is much wider. For a good calibration you also want samples from the non overlapping areas of images as well, that is why it is split up in 3 parts.

**Comment by JimmyDaSilva** [comment]
Oh I see. We need to get to the corners of the RGB image at some point.
Thank you! It makes sense to me now.
