### ISSUE TITLE
fail to detect checkerboard on IR image

### ISSUE THREAD

**Issue by leoujz** [code-iai/iai_kinect2#379]
I fail to detect checkerboard on the IR image. I have been looking for independent IR light source these days, but they do not work. I don't know whether this is a right way to solve it, or just there's something wrong with my IR light source.

Are there some special setups for capturing the IR image by Kinect V2?

**Comment by wiedemeyer** [comment]
Is the pattern visible in the window? If not you might used an ink based printer. Some inks might not be visible on ir. Try to print it with a laser printer.

**Comment by leoujz** [comment]
Thank you very much, a ink printer is used, now I have tried laser printer
and pattern can be detected. Thank you again.

2017-03-09 3:48 GMT+08:00 Thiemo Wiedemeyer <notifications@github.com>:
