### ISSUE TITLE
How to make sure that the kinect2_bridge is actually using the calibration files

### ISSUE THREAD

**Issue by vacky11** [code-iai/iai_kinect2#392]
I have followed the entire process of calibrating kinect2 and finally have placed the 4 calibration files in kinect2_bridge/data/$serial.
But there is no difference in the pre-calibration and post calibration results 

How can I make sure that the new calibrated files are actually being used?

**Comment by xuhangxx** [comment]
I am facing the same problem, I repeated the calibration process for many times and made sure that I am not missing anything. Who can help me!!!

**Comment by wiedemeyer** [comment]
While stating up kinect2_bridge, it will tell you if it used the defaults or loaded a calibration.

**Comment by TrinhTUHH** [comment]
@vacky11  and @xuhangxx , have you found the solution? I also create a folder with serial name and place 4 calibrated files there, but it seems like the calibrated files are not loader. When I run kinect2_bridge it always said "sing sensor defaults for..."

**Comment by vacky11** [comment]
@TrinhTUHH 
I dont have access to Kinect2 anymore. So I cant verify this. Sorry about that.
