### ISSUE TITLE
Maker error under 14.04 and ROS Indigo: Eigen cannot be found

### ISSUE THREAD

**Issue by cschindlbeck** [code-iai/iai_kinect2#400]
I am not  able to make the iai_kinect under ROS Indigo and Ubuntu 14.04:

``` 
/home/cschindlbeck/catkin_ws/src/iai_kinect2/kinect2_registration/src/depth_registration_cpu.h:22:26: fatal error: Eigen/Geometry: No such file or directory
 #include <Eigen/Geometry>
                          ^
compilation terminated.
```

It worked for me previously and i have installed eigen3, do i need to change something in ROS globally or in the iai_kinect package?

Thanks in advance

**Comment by mallela** [comment]
Install latest version of Eigen from [here](http://eigen.tuxfamily.org/index.php?title=Main_Page#Download).

**Comment by cschindlbeck** [comment]
Thanks!
