### ISSUE TITLE
[Q] Standalone version of kinect2_calibration (without ROS)?

### ISSUE THREAD

**Issue by floe** [code-iai/iai_kinect2#409]
Hi, I'm currently looking at a scenario where I can't use ROS, but would still like to use a separately calibrated Kinect camera. From a quick look, it seems that kinect2_calibration uses ROS only for acquiring the color/depth/IR images, is that correct? Then I'd probably give it a try to implement a standalone version that uses libfreenect2 directly.

**Comment by wiedemeyer** [comment]
Hi @floe 
Yes, it just uses ROS for receiving the images. The calibration itself is done with OpenCV. I think it should be possible to reuse the code directly with libfreenect2. Another solution would be to simply calibrate the camera on a ROS system and then just copy the calibration data to the other systems.

**Comment by floe** [comment]
Thanks. AFAICS kinect2_registration also isn't really tied to ROS, correct?

**Comment by wiedemeyer** [comment]
kinect2_registration does not even use ROS (except for output), it is only a lib.

**Comment by remmel** [comment]
Hi @floe did you managed to do something? In that case do you have a repository to share?
THanks!

**Comment by floe** [comment]
Sorry, never got around to implementing this. Using Kinect Azure now.
