### ISSUE TITLE
[rospack] Error: package 'kinect2_calibration' not found

### ISSUE THREAD

**Issue by marcx95** [code-iai/iai_kinect2#426]
Hello,
I follow the instructions and "roslaunch kinect2_bridge kinect2_bridge.launch" runs perfectly, but when I try to run:
rosrun kinect2_calibration kinect2_calibration chess5x7x0.03 record color
[rospack] Error: package 'kinect2_calibration' not found
and
rosrun kinect2_viewer kinect2_viewer kinect2 sd cloud
[rospack] Error: package 'kinect2_viewer' not found
I am using Ubuntu 14.04 and ros indigo, the Protonect example works.

**Comment by wuguangbin1230** [comment]
hi, do you solve this problem?
