### ISSUE TITLE
How to use it with opencv ?

### ISSUE THREAD

**Issue by Abduoit** [code-iai/iai_kinect2#438]
Hi, all and @wiedemeyer 

I want to use kinect v2 rgb stream in order to feed it to Yolo v2. I know that I have to convert the streaming images into cv::mat in OpenCV. Since I am new in libfreenect2 and OpenCv, I don't know how to do that?

I have kinect v2 and Yolo v2, both works properly. I already install opencv, iai_kinect2 and libfreenect2.

Anyone can help me for this ???

**Comment by bbferka** [comment]
Hi @Abduoit, 

You should check out the ROS tutorials on how to convert ROS messages into [cv::Mat.](http://wiki.ros.org/cv_bridge/Tutorials) If you don't want to use ROS, iai_kinect2 is not the right tool for you.
