### ISSUE TITLE
no Topic names  /kinect2/.../points

### ISSUE THREAD

**Issue by MorganLeee** [code-iai/iai_kinect2#459]
I only get those topics below with no topic names  /kinect2/.../points
In ubuntu 16.04
can anyone help me with this issue?
`~$ rostopic list

/kinect2/hd/camera_info

/kinect2/hd/image_color

/kinect2/hd/image_color/compressed

/kinect2/hd/image_color_rect

/kinect2/hd/image_color_rect/compressed

/kinect2/hd/image_depth_rect

/kinect2/hd/image_depth_rect/compressed

/kinect2/hd/image_mono

/kinect2/hd/image_mono/compressed

/kinect2/hd/image_mono_rect

/kinect2/hd/image_mono_rect/compressed

/kinect2/qhd/camera_info

/kinect2/qhd/image_color

/kinect2/qhd/image_color/compressed

/kinect2/qhd/image_color_rect

/kinect2/qhd/image_color_rect/compressed

/kinect2/qhd/image_depth_rect

/kinect2/qhd/image_depth_rect/compressed

/kinect2/qhd/image_mono

/kinect2/qhd/image_mono/compressed

/kinect2/qhd/image_mono_rect

/kinect2/qhd/image_mono_rect/compressed

/kinect2/sd/camera_info

/kinect2/sd/image_color_rect

/kinect2/sd/image_color_rect/compressed

/kinect2/sd/image_depth

/kinect2/sd/image_depth/compressed

/kinect2/sd/image_depth_rect

/kinect2/sd/image_depth_rect/compressed

/kinect2/sd/image_ir

/kinect2/sd/image_ir/compressed

/kinect2/sd/image_ir_rect

/kinect2/sd/image_ir_rect/compressed

/rosout

/rosout_agg
`

**Comment by jdeeee** [comment]
Hey,

how did you start the kinect2_bridge? You need to use the launch file to do so (kinect2_bridge.launch). Within this launch file you will find nodes using depth_image_proc that publish the points.
