### ISSUE TITLE
kinect2_bridge crashes

### ISSUE THREAD

**Issue by mihaimorariu** [code-iai/iai_kinect2#5]
Hello, 

I am using Ubuntu 14.04 with ROS Indigo and I am trying to get the Kinect2 tools to work. I first tried to install libfreenect2 (from https://github.com/wiedemeyer/libfreenect2) by running install_ubuntu.sh and then by building Protonect. However, during this process I got an error saying that the file CL/cl.hpp was not found.

My question is: what is the correct way to install this modified version of libfreenect2? I installed OpenCL as well (although the description page says it's optional) and managed to eventually compile libfreenect2. But, when I run kinect2_bridge, I get the following error:

Using OpenCL registration method!
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 10 usb devices connected
[Freenect2Impl] found valid Kinect v2 @4:1 with serial 502205743042
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] opened

starting kinect2

[Freenect2DeviceImpl] starting...
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41    ............C..A
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x0020:  0a 21 33 55 20 00 17 ba 00 08 00 00 10 00 00 00    .!3U ...........
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    ................
0x0040:  31 33 00 00 00 02 10 18 47 4e 4b 39 32 31 2e 31    13......GNK921.1
0x0050:  58 00 00 00 00 00 00 00 00 00 00 00                X...........

ERROR: clGetPlatformIDs(-1001)
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)

Has anyone experienced this? I really cannot get this to work on my system (Intel Core i5, 4GB RAM, Intel HD Graphics 4000, Ubuntu 14.04, ROS Indigo). Is it possible to avoid using OpenCL?

Regards,

Mihai Morariu

**Comment by sketchc89** [comment]
Can confirm, was receiving the exact same errors after not properly following direction in libfreenect2. I only installed `opencl-headers`. After reading this I installed `nvidia-opencl-icd-352` from `ppa:xorg-edgers` and it resolved the issue.
Thank you

**Comment by KahnShi** [comment]
@sketchc89  I had the same problem with you and I just solved it by add sudo before ./Protonect cl.
It takes me a lot of time to find this solution and it worked for me.
Maybe you can have a try.

**Comment by JimmyDaSilva** [comment]
I confirm what sketchc89 said. I was having the exact same problem. Running ```sudo ./Protonect cl``` once solved the problem once and for all. I can now run kinect2_bridge as well. I have no clue about what changed by running in sudo mode once, but it works now!

**Comment by wiedemeyer** [comment]
If you install nvidia-modprobe the sudo problem should be solved.
