### ISSUE TITLE
Kinect2 Bridge Nodelet Support

### ISSUE THREAD

**Issue by mitchellwills** [code-iai/iai_kinect2#51]
With the amount of data that kinect2_bridge publishes it would be nice to have a nodelet version of it.

**Comment by wiedemeyer** [comment]
Hi,
just added a nodelet wrapper for kinect2_bridge to the devel branch. Feel free to test it. I also modified the launch file to use the nodelet version together with the point cloud nodelets.

**Comment by mitchellwills** [comment]
Thanks. Works great.
Would have made a PR, but I wasn't sure what was up with the threading.
