### ISSUE TITLE
Provide a sample calibration

### ISSUE THREAD

**Issue by xlz** [code-iai/iai_kinect2#53]
Can you provide a sample calibration file as default for testing?

**Comment by wiedemeyer** [comment]
Hi,
there are two folders with example calibrations. Or do you mean kinect2_bridge should load a default calibration if no calibration for the specific sensor is provided?

**Comment by xlz** [comment]
Ahh, I didn't look hard enough.

Your idea is good though.

**Comment by wiedemeyer** [comment]
They are located in [kinect2_bridge/data/<serialnumber>](https://github.com/code-iai/iai_kinect2/tree/master/kinect2_bridge/data/299150235147).
Right now the defaults are the intrinsics reported by the sensor, with no extrinsics. Becauce I don't have default values for the extrinsic parameters that work well for all sensors.
