### ISSUE TITLE
would it work at ROS Noetic Ninjemys

### ISSUE THREAD

**Issue by MengHao666** [code-iai/iai_kinect2#557]

**Comment by ACarfi** [comment]
It works for me. I had to change few things in the source code to make it work with opencv 4.2 but just minor modifications.

Anyway I am having problems with the reference frame that I am trying to solve right now.

**Comment by MengHao666** [comment]
> It works for me. I had to change few things in the source code to make it work with opencv 4.2 but just minor modifications.
> 
> Anyway I am having problems with the reference frame that I am trying to solve right now.

wonderful thing! Could u publish it when u finally successed?
I want to write python3 code with ROS and the KinectV2 device ,So I wanted this repo could work at  ROS Noetic Ninjemys .
But as I compile without any modification,it just failed to get the data of KinectV2

**Comment by ACarfi** [comment]
I have uploaded my edited version here: https://github.com/TheEngineRoom-UniGe/iai_kinect2.git
for me it works!

**Comment by MengHao666** [comment]
Well done!
I will try it in the near future and see if it works for me!
Thanks for it in advance!

**Comment by Ktysai** [comment]
> I have uploaded my edited version here: https://github.com/TheEngineRoom-UniGe/iai_kinect2.git
> for me it works!

**@ACarfi** 
An interesting solution. I have not tried exactly your code but something similar. For ROS2 implementation you have some solutions?

**Comment by ACarfi** [comment]
@Ktysai no I am sorry. I have jet no experience with ROS2.

**Comment by fred-lyu** [comment]
> I have uploaded my edited version here: https://github.com/TheEngineRoom-UniGe/iai_kinect2.git for me it works!

Ohooo,thank u for this interesting solution

**Comment by MengHao666** [comment]
> It works for me. I had to change few things in the source code to make it work with opencv 4.2 but just minor modifications.
> 
> Anyway I am having problems with the reference frame that I am trying to solve right now.

long time . I don't need to solve it now. hhhh.
