### ISSUE TITLE
About kinect2_brdige.launch 's queue_size

### ISSUE THREAD

**Issue by aginika** [code-iai/iai_kinect2#56]
Hi!

I am using kinect2_bridge.launch to visualize the point clouds in rviz.
But, when I launched as `roslaunch kinect2_bridge kinect2_bridge.launch`,
it didn't publish any points in /kinect2/depth_{lowres | high_res}/points.

So, I changed the launch file's depth_image_proc queue_size from 2 to 4.
Then, the pointcloud is published correctly.

I'm just curious, but is my environment set up wrongly? If then, what should I do?

Thanks.

**Comment by wiedemeyer** [comment]
Hi,
I have no clue what the problem could be, but good to hear that it is working now.

**Comment by aginika** [comment]
Hmm, all right.
Thank you.

**Comment by lywind** [comment]
I encountered the same problem and fixed it just using your advice.
