### ISSUE TITLE
Beignet install

### ISSUE THREAD

**Issue by tysonhammen** [code-iai/iai_kinect2#58]
Not sure if you want to add the notes here or not but just installing the lllvm and clang packages will not let Beignet build. I had to add a couple of additional sym links to allow "make" to run. They are below.

sudo ln -s /usr/lib/llvm-3.5/bin/llvm-as /usr/bin/llvm-as
sudo ln -s /usr/lib/llvm-3.5/bin/llvm-link /usr/bin/llvm-link

**Comment by mitchellwills** [comment]
I had to do something similar

**Comment by wiedemeyer** [comment]
Did you installed llvm 3.5 from the Ubuntu packages? The Ubuntu package has some [issues](https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-3.5/+bug/1372062), some files are located in wrong directories. Please use the one provided from http://llvm.org.

**Comment by tysonhammen** [comment]
Got it. Yes, I just installed through apt.
