### ISSUE TITLE
when calibrate ir, calibration pattern not detected 

### ISSUE THREAD

**Issue by flobotics** [code-iai/iai_kinect2#80]
hi,
i want to calibrate the kinect2 and i can run:
rosrun kinect2_calibration kinect2_calibration chess5x7x0.03 record color

which shows me the calibration pattern over the chess pattern and i can record a image with space-bar. Also i can calibrate color.

But when i run:

rosrun kinect2_calibration kinect2_calibration chess5x7x0.03 record ir

it does not show the calibration pattern over the chess pattern ? I tried to tune it a little bit with the l,h,1,2,3,4 keyboard shortcuts, but no calibration pattern is showing up ?

what do i wrong ?
flo

**Comment by pammirato** [comment]
did you input the correct pattern?  i.e is your board 5x7?  
remember this not the number of squares but the number of intersections.

**Comment by pammirato** [comment]
also my calibration efforts are not going well.

I also have trouble detecting the pattern, and even when i do the depth is still misaligned. 
I get errors of about .2 when calibrating the color,ir,and sync. But when I run the registration viewer the results are not good.

**Comment by pammirato** [comment]
hahah nevermind when i was running registration viewer I had on the 'raw' option. woops

**Comment by flobotics** [comment]
i use the orginal 5x7x0.03  and i measured it and it is exactly 3x3cm squares.

The color (which is mono) detects it directly, but not the ir. I only see a white paper on ir image ?

**Comment by wiedemeyer** [comment]
The ir emitter is pretty strong. Move the pattern further away from the camera. 50 to 150 cm. Once the pattern is recognized the calibration tool should adjust the brightness automatically.

**Comment by flobotics** [comment]
it does not work with ir. 

In the image that is shown when running "rosrun kinect2_calibration kinect2_calibration chess5x7x0.03 record ir" i by myself can never see the black squares, even how far or near i am at the kinect ?  Is that normal ?

**Comment by wiedemeyer** [comment]
No, never seen that. could you add a screenshot?

**Comment by flobotics** [comment]
![screenshot 2015-04-20 15 33 46](https://cloud.githubusercontent.com/assets/11964445/7231012/c46eff14-e772-11e4-9bf4-0c3b5291657c.png)

**Comment by wiedemeyer** [comment]
I just talked to a colleague. He said some inks might be transparent to IR. Are you using an ink printer? Could you try it on a laser printer? If that's true, what type of printer and ink are you using? (just out of curiosity)

**Comment by flobotics** [comment]
yes, it was an ink-printer. it was not mine, so i dont know the printer/ink info.  I will try it with an laser printer, but that will take until tomorrow.

**Comment by flobotics** [comment]
yes, seemed  so.
i printed it on a laser printer and now it directly gets it
![screenshot 2015-04-21 17 23 25](https://cloud.githubusercontent.com/assets/11964445/7255715/5298ab36-e84b-11e4-87dd-5cfda70bc389.png)

thanks for the tip
