### ISSUE TITLE
Run 2 kinects at the same time

### ISSUE THREAD

**Issue by peterkty** [code-iai/iai_kinect2#82]
I did it by running the kinect_bridge twice and providing the corresponding serial number.

I could get data when I ran the first one. But when I ran the second one, the first one failed with
"""
[TransferPool::submit] failed to submit transfer
"""
and the second one would not run:
"""
starting main loop

[kinect2_2-1] process has died [pid 17875, exit code -11, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=kinect2_2 __log:=/home/xx/.ros/log/36a509e8-e76e-11e4-b9aa-6805ca2fd8ae/kinect2_2-1.log].
"""

Has anyone successfully run two kinects on a computer?

**Comment by wiedemeyer** [comment]
There is already an issue on this topic. #43
You should also look at the issues for libfreenect2. https://github.com/OpenKinect/libfreenect2/issues/97
