### ISSUE TITLE
Cloud Viewer show nothing ,use Intel CPU/GPU  and OpenCL

### ISSUE THREAD

**Issue by YuweiGuo** [code-iai/iai_kinect2#84]
hallo , 
when I run cloud viewer with intel GPU, I have a problem , the cloud viewer show nothing . this is my computer :
system : Ubuntu 14.04
cpu : Intel® Core™ i7-3630QM CPU @ 2.40GHz × 8 
graphics : Nvidia Quadro K3000M and Intel(R) HD Graphics IvyBridge M GT2 . 

when I use the Nvidia card and OpenCL , the programm run gut . 
then I install the Beignet for Intel GPU . and then I start the Kinect_bridge the second time.

the following is my steps:

1----Nvidia Karte driver 331 , opencl-icd-331 , cuda-dev ...

2----reboot

3----OpenCV

4----PCL

5----ROS

7----iai-kinectv2   run gut  , image and cloud

8----switch the Graphic cart to  Intel  , can not find opencl device 

9----Intel opencl install , Beignet 1.0.0

10---- run gut.

11----reboot

11---- and then I switch back to Nvidia card

the viewer show it self gut , but the programm show that , it use the Intel card as a OpenCL device. 
I get the following output (note : I still use Nvidia card now):
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
modprobe: ERROR: could not insert 'nvidia_331_updates': No such device
parameter:
        base_name: kinect2
           sensor: 
        fps_limit: -1
       calib_path: /home/yuwei/Groupprojekt/ros_kinectV2_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: opencl     // different
     depth_device: -1
       reg_method: opencl    
       reg_devive: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 2
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4

[OpenCLDepthPacketProcessor::listDevice]  devices:
  0: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[OpenCLDepthPacketProcessor::init]  selected device: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 14 usb devices connected
[Freenect2Impl] found valid Kinect v2 @4:5 with serial 039374243547
[Freenect2Impl] found 1 devices
Kinect2 devices found: 
  0: 039374243547 (selected)
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] opened

starting kinect2

[Freenect2DeviceImpl] starting...
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41    2e2e2e2e2e2e2e2e2e2e2e2e432e2e41
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e
0x0020:  0a 21 33 55 c2 00 17 20 00 08 00 00 10 00 00 00    2e2133552e2e2e202e2e2e2e2e2e2e2e
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    2e2e2e2e2e2e2e2e2e2e802e2e2e2e2e
0x0040:  31 33 00 00 00 03 13 01 47 4b 55 30 34 35 2e 31    31332e2e2e2e2e2e474b553034352e31
0x0050:  58 00 00 00 00 00 00 00 07 00 00 00                582e2e2e2e2e2e2e2e2e2e2e

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  01 26 00 00                                        2e262e2e

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  03 26 00 00                                        2e262e2e

[Freenect2DeviceImpl] enabling usb transfer submission...
[Freenect2DeviceImpl] submitting usb transfers...
[Freenect2DeviceImpl] started

device serial: 039374243547
device firmware: 4.3.3913.0.7

default ir camera parameters: 
fx 365.604, fy 365.604, cx 255.156, cy 207.491
k1 0.0897843, k2 -0.271625, p1 0, p2 0, k3 0.0963501

default color camera parameters: 
fx 1081.37, fy 1081.37, cx 959.5, cy 539.5
using sensor defaults for color intrinsic parameters.
using sensor defaults for ir intrinsic parameters.
using defaults for rotation and translation.
using defaults for depth shift.
[DepthPacketStreamParser::handleNewData] not all subsequences received 0

camera parameters used:
camera matrix color:
[1081.3720703125, 0, 959.5;
  0, 1081.3720703125, 539.5;
  0, 0, 1]
distortion coefficients color:
[0, 0, 0, 0, 0]
camera matrix ir:
[365.6040954589844, 0, 255.1558074951172;
  0, 365.6040954589844, 207.4907989501953;
  0, 0, 1]
distortion coefficients ir:
[0.08978427946567535, -0.2716245949268341, 0, 0, 0.09635014086961746]
rotation:
[1, 0, 0;
  0, 1, 0;
  0, 0, 1]
translation:
[-0.052;
  0;
  0]
depth shift:
0

[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistrationOpenCL::listDevice]  devices:
  0: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[DepthRegistrationOpenCL::init]  selected device: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[DepthRegistrationOpenCL::listDevice]  devices:
  0: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[DepthRegistrationOpenCL::init]  selected device: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
starting main loop

[kinect2_bridge] depth processing: ~9574.58Hz (0.104443ms) publishing rate: ~29.9097Hz
[kinect2_bridge] color processing: ~4410.79Hz (0.226717ms) publishing rate: ~28.9127Hz

[OpenCLDepthPacketProcessor] avg. time: 75.6696ms -> ~13.2153Hz
[TurboJpegRgbPacketProcessor] avg. time: 21.3444ms -> ~46.8507Hz
[kinect2_bridge] depth processing: ~11.1505Hz (89.6822ms) publishing rate: ~11.6648Hz
[kinect2_bridge] color processing: ~58.4754Hz (17.1012ms) publishing rate: ~29.9951Hz
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 1022
[TurboJpegRgbPacketProcessor] avg. time: 20.6317ms -> ~48.4692Hz
[kinect2_bridge] depth processing: ~14.4668Hz (69.1236ms) publishing rate: ~13.3295Hz
[kinect2_bridge] color processing: ~57.4931Hz (17.3934ms) publishing rate: ~29.9914Hz
[TurboJpegRgbPacketProcessor] avg. time: 19.5051ms -> ~51.2686Hz
[OpenCLDepthPacketProcessor] avg. time: 11.9676ms -> ~83.5591Hz
[kinect2_bridge] depth processing: ~9033.46Hz (0.1107ms) publishing rate: ~30.2462Hz
[kinect2_bridge] color processing: ~4153.78Hz (0.240744ms) publishing rate: ~29.9138Hz
[TurboJpegRgbPacketProcessor] avg. time: 19.2443ms -> ~51.9635Hz
[OpenCLDepthPacketProcessor] avg. time: 11.9734ms -> ~83.5186Hz
^C[kinect2_bridge] depth processing: ~9410.13Hz (0.106268ms) publishing rate: ~29.9279Hz
[kinect2_bridge] color processing: ~4258.85Hz (0.234805ms) publishing rate: ~29.9279Hz
[Freenect2DeviceImpl] stopping...
[Freenect2DeviceImpl] disabling usb transfer submission...
[Freenect2DeviceImpl] canceling usb transfers...
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!

[Freenect2DeviceImpl] stopped
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] releasing usb interfaces...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] already closed, doing nothing  
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

now I think , it will be OK , when I use Intel card to run it. and I do it.
I use the Nvidia prime indicator to switch graphic card back to Intel  . but now the cloud viewer show nothing. 
I have install the Beignet .  OpenCL-headers , llvm-3.5 ..... 
this is the output of kinect_bridge :

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

modprobe: ERROR: could not insert 'nvidia_331_updates': No such device
parameter:
        base_name: kinect2
           sensor: 
        fps_limit: -1
       calib_path: /home/yuwei/Groupprojekt/ros_kinectV2_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: opengl	// different
     depth_device: -1
       reg_method: opencl
       reg_devive: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 2
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4

[Freenect2Impl] enumerating devices...
[Freenect2Impl] 14 usb devices connected
[Freenect2Impl] found valid Kinect v2 @4:3 with serial 039374243547
[Freenect2Impl] found 1 devices
Kinect2 devices found: 
  0: 039374243547 (selected)
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] opened

starting kinect2

[Freenect2DeviceImpl] starting...
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41    2e2e2e2e2e2e2e2e2e2e2e2e432e2e41
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e
0x0020:  0a 21 33 55 c2 00 17 20 00 08 00 00 10 00 00 00    2e2133552e2e2e202e2e2e2e2e2e2e2e
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    2e2e2e2e2e2e2e2e2e2e802e2e2e2e2e
0x0040:  31 33 00 00 00 03 13 01 47 4b 55 30 34 35 2e 31    31332e2e2e2e2e2e474b553034352e31
0x0050:  58 00 00 00 00 00 00 00 07 00 00 00                582e2e2e2e2e2e2e2e2e2e2e

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  01 26 00 00                                        2e262e2e

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  03 26 00 00                                        2e262e2e

[Freenect2DeviceImpl] enabling usb transfer submission...
[Freenect2DeviceImpl] submitting usb transfers...
[Freenect2DeviceImpl] started

device serial: 039374243547
device firmware: 4.3.3913.0.7

default ir camera parameters: 
fx 365.604, fy 365.604, cx 255.156, cy 207.491
k1 0.0897843, k2 -0.271625, p1 0, p2 0, k3 0.0963501

default color camera parameters: 
fx 1081.37, fy 1081.37, cx 959.5, cy 539.5
using sensor defaults for color intrinsic parameters.
using sensor defaults for ir intrinsic parameters.
using defaults for rotation and translation.
using defaults for depth shift.
[DepthPacketStreamParser::handleNewData] not all subsequences received 0
[DepthPacketStreamParser::handleNewData] not all subsequences received 512

camera parameters used:
camera matrix color:
[1081.3720703125, 0, 959.5;
  0, 1081.3720703125, 539.5;
  0, 0, 1]
distortion coefficients color:
[0, 0, 0, 0, 0]
camera matrix ir:
[365.6040954589844, 0, 255.1558074951172;
  0, 365.6040954589844, 207.4907989501953;
  0, 0, 1]
distortion coefficients ir:
[0.08978427946567535, -0.2716245949268341, 0, 0, 0.09635014086961746]
rotation:
[1, 0, 0;
  0, 1, 0;
  0, 0, 1]
translation:
[-0.052;
  0;
  0]
depth shift:
0

[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistrationOpenCL::listDevice]  devices:
  0: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[DepthRegistrationOpenCL::init]  selected device: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[DepthRegistrationOpenCL::listDevice]  devices:
  0: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[DepthRegistrationOpenCL::init]  selected device: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
starting main loop

[kinect2_bridge] depth processing: ~10592.3Hz (0.0944086ms) publishing rate: ~30.5835Hz
[kinect2_bridge] color processing: ~5194.99Hz (0.192493ms) publishing rate: ~29.2538Hz
[OpenGLDepthPacketProcessor] avg. time: 3.32281ms -> ~300.95Hz
[TurboJpegRgbPacketProcessor] avg. time: 18.9232ms -> ~52.8452Hz
[kinect2_bridge] depth processing: ~10754.6Hz (0.0929832ms) publishing rate: ~29.9228Hz
[kinect2_bridge] color processing: ~5466.79Hz (0.182923ms) publishing rate: ~29.9228Hz
^C[TurboJpegRgbPacketProcessor] avg. time: 19.5182ms -> ~51.2343Hz
[Freenect2DeviceImpl] stopping...
[Freenect2DeviceImpl] disabling usb transfer submission...
[Freenect2DeviceImpl] canceling usb transfers...
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[Freenect2DeviceImpl] stopped
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] releasing usb interfaces...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] already closed, doing nothing

///////////////////////////////////////////////////////////////////////////////////////////

and then I try to use Intel card only . 
ubuntu new install , and all dependens.
the cloud viewer show nothing too. 
this is the output from bridge :

/////////////////////////////////////////////////////////////////////////////////////////

parameter:
        base_name: kinect2
           sensor: 
        fps_limit: -1
       calib_path: /home/yuwei/Groupprojekt/ros_kinectV2_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: opengl   //different
     depth_device: -1
       reg_method: opencl   
       reg_devive: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 2
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4

[Freenect2Impl] enumerating devices...
[Freenect2Impl] 14 usb devices connected
[Freenect2Impl] found valid Kinect v2 @4:3 with serial 039374243547
[Freenect2Impl] found 1 devices
Kinect2 devices found: 
  0: 039374243547 (selected)
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] opened

starting kinect2

[Freenect2DeviceImpl] starting...
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41    2e2e2e2e2e2e2e2e2e2e2e2e432e2e41
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e
0x0020:  0a 21 33 55 c2 00 17 20 00 08 00 00 10 00 00 00    2e2133552e2e2e202e2e2e2e2e2e2e2e
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    2e2e2e2e2e2e2e2e2e2e802e2e2e2e2e
0x0040:  31 33 00 00 00 03 13 01 47 4b 55 30 34 35 2e 31    31332e2e2e2e2e2e474b553034352e31
0x0050:  58 00 00 00 00 00 00 00 07 00 00 00                582e2e2e2e2e2e2e2e2e2e2e

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  0d 26 00 00                                        2e262e2e

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  03 26 00 00                                        2e262e2e

[Freenect2DeviceImpl] enabling usb transfer submission...
[Freenect2DeviceImpl] submitting usb transfers...
[Freenect2DeviceImpl] started

device serial: 039374243547
device firmware: 4.3.3913.0.7

default ir camera parameters: 
fx 365.604, fy 365.604, cx 255.156, cy 207.491
k1 0.0897843, k2 -0.271625, p1 0, p2 0, k3 0.0963501

default color camera parameters: 
fx 1081.37, fy 1081.37, cx 959.5, cy 539.5
using sensor defaults for color intrinsic parameters.
using sensor defaults for ir intrinsic parameters.
using defaults for rotation and translation.
using defaults for depth shift.
[DepthPacketStreamParser::handleNewData] not all subsequences received 0

camera parameters used:
camera matrix color:
[1081.3720703125, 0, 959.5;
  0, 1081.3720703125, 539.5;
  0, 0, 1]
distortion coefficients color:
[0, 0, 0, 0, 0]
camera matrix ir:
[365.6040954589844, 0, 255.1558074951172;
  0, 365.6040954589844, 207.4907989501953;
  0, 0, 1]
distortion coefficients ir:
[0.08978427946567535, -0.2716245949268341, 0, 0, 0.09635014086961746]
rotation:
[1, 0, 0;
  0, 1, 0;
  0, 0, 1]
translation:
[-0.052;
  0;
  0]
depth shift:
0

[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistrationOpenCL::listDevice]  devices:
  0: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[DepthRegistrationOpenCL::init]  selected device: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[DepthRegistrationOpenCL::listDevice]  devices:
  0: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
[DepthRegistrationOpenCL::init]  selected device: Intel(R) HD Graphics IvyBridge M GT2 (GPU)[Intel]
starting main loop

[kinect2_bridge] depth processing: ~11372.4Hz (0.0879319ms) publishing rate: ~30.2568Hz
[kinect2_bridge] color processing: ~4950.52Hz (0.201999ms) publishing rate: ~29.9243Hz
[OpenGLDepthPacketProcessor] avg. time: 3.20967ms -> ~311.558Hz
[TurboJpegRgbPacketProcessor] avg. time: 20.0318ms -> ~49.9206Hz
[kinect2_bridge] depth processing: ~10596.7Hz (0.0943687ms) publishing rate: ~29.9184Hz
[kinect2_bridge] color processing: ~5377.31Hz (0.185966ms) publishing rate: ~29.9184Hz
[OpenGLDepthPacketProcessor] avg. time: 2.97309ms -> ~336.35Hz
[TurboJpegRgbPacketProcessor] avg. time: 18.5328ms -> ~53.9584Hz
[kinect2_bridge] depth processing: ~11086.6Hz (0.090199ms) publishing rate: ~29.9149Hz
[kinect2_bridge] color processing: ~5074.64Hz (0.197058ms) publishing rate: ~29.9149Hz
[OpenGLDepthPacketProcessor] avg. time: 3.02261ms -> ~330.84Hz
[TurboJpegRgbPacketProcessor] avg. time: 20.0109ms -> ~49.9728Hz
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 1021
[kinect2_bridge] depth processing: ~11139.6Hz (0.0897699ms) publishing rate: ~29.9123Hz
[kinect2_bridge] color processing: ~4892.79Hz (0.204382ms) publishing rate: ~30.2446Hz
^C[Freenect2DeviceImpl] stopping...
[Freenect2DeviceImpl] disabling usb transfer submission...
[Freenect2DeviceImpl] canceling usb transfers...
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[Freenect2DeviceImpl] stopped
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] releasing usb interfaces...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] already closed, doing nothing

/////////////////////////////////////////////////////////

the following is my steps:

0----ubuntu 14.04 new install

1----install opencv

2----install pcl

3----install ros

4----install libfreenect2 , rgb run gut , but ir and cloud show nothing

5----install iai_kinect2 , bridge show  that  using CPU registration method , image run gut but cloud show nothing ,

6----install intel OpenCL , beignet 1.0.0 , image run gut but cloud show nothing 

7----compile iai_kinect2 onece mal , image run gut but cloud show nothing 

what have I make false? 
thank you!

yuwei

**Comment by wiedemeyer** [comment]
Is `Protonect` working?
So if you use OpenCL as `depth_method` it works, but with `OpenGL` it doesn't. So just use OpenCL, `depth_method:=opencl` as a parameter.

**Comment by YuweiGuo** [comment]
The Protonect is working , but just for the nvidia card . Intel not work.
Yes , I think so too, how can I fix it?

**Comment by YuweiGuo** [comment]
Rewrite the kinect2_bridge.cpp?

**Comment by wiedemeyer** [comment]
libfreenect2 has to be compiled with OpenCL support. And kinect2_bridge has to be compiled after it. Then it should use OpenCL as default.
You can change it on start via parameters, for example:
`roslaunch kinect2_bridge kinect2_bridge depth_method:=opencl`
