### ISSUE TITLE
Can't give multiple arguments to kinect2_bridge

### ISSUE THREAD

**Issue by pammirato** [code-iai/iai_kinect2#85]
When i try to run:

rosrun kinect2_bridge kinect2_bridge  _reg_method:=cpu _sensor:=500317541942

I get a seg fault. 

I solved the issue by adding argv[1] = "";   in the main function, here:

argv[0] = defaultParam;
++argc;

argv[1] = "";

**Comment by wiedemeyer** [comment]
Hi,
thanks for pointing this out. You are using the devel branch, right? But that code will be removed soon anyway.

**Comment by pammirato** [comment]
yea it was the devel branch
