### ISSUE TITLE
Install on Ubuntu 14.04

### ISSUE THREAD

**Issue by davetcoleman** [code-iai/iai_kinect2#9]
I am having problems installing the dependencies - I'm taking notes to improve the documentation but please help me figure it out...

First install basic dependencies: 

```
sudo apt-get install libusb-dev libturbojpeg opencl-headers 
```

Then install

```
git clone https://github.com/wiedemeyer/libfreenect2.git
cd libfreenect2/depends
sh install_ubuntu.sh

# might be required:
sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.0.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so

# continue:
cd ../examples/protonect/
cmake CMakeLists.txt
make && sudo make install
```

But then I get the error 

```
Linking C shared library /home/dave/ros/ws_base/src/libfreenect2/examples/protonect/lib/libglfw.so
[ 46%] Built target glfw
Linking CXX executable bin/generate_resources_tool
[ 48%] Built target generate_resources_tool
[ 51%] Generating src/resources.inc
Scanning dependencies of target freenect2
[ 53%] Building CXX object CMakeFiles/freenect2.dir/src/transfer_pool.cpp.o
In file included from /home/dave/ros/ws_base/src/libfreenect2/examples/protonect/src/transfer_pool.cpp:27:0:
/home/dave/ros/ws_base/src/libfreenect2/examples/protonect/include/libfreenect2/usb/transfer_pool.h:30:20: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
                    ^
compilation terminated.
```

It appears it is looking for a directoy that does not exist in the CMakeLists.txt:

```
INCLUDE_DIRECTORIES("${DEPENDS_DIR}/libusb/include/libusb-1.0/")
```

Because libusb has been renamed to libusb_src in the repo. Also, there does not appear to be any include subfolder in that libusb_src folder.

I have double checked that I have the following Ubuntu packages installed:
- libusb-0.1-4
- libusb-1.0.0
- libusb-1.0.0-dev
- libusb-1.0-doc
- libusb-dev
- libusbmuxd2

Any help is appreciated!

**Comment by DrFuzzy** [comment]
Succesfully installed libfreenect2 in Ubuntu 14.04 x64. Unfortunatelly when I run ./bin/Protonect, after the Kinect has been detected (Kinect for Windows), I get some libusb busy error:

delk@Darwin:~/libfreenect2/examples/protonect$ ./bin/Protonect
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 11 usb devices connected
[Freenect2Impl] found valid Kinect v2 @2:4 with serial 503XXXXXX542
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[UsbControl::claimInterfaces(IrInterfaceId)] failed! libusb error -6: LIBUSB_ERROR_BUSY
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] failed to open Kinect v2 @2:4!
no device connected or failure opening the default one!

Any ideas how to resolve this?

**Comment by wiedemeyer** [comment]
Try it with `sudo ./bin/Protonect`. If that works, you forgot to set the device permissions, like described [here](https://github.com/code-iai/iai_kinect2#permissions-to-access-the-kinect-one).

**Comment by DrFuzzy** [comment]
I have set the device permissions. Nope, same issue with sudo:

delk@Darwin:~/libfreenect2/examples/protonect$ sudo ./bin/Protonect
[sudo] password for delk: 
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 11 usb devices connected
[Freenect2Impl] found valid Kinect v2 @2:4 with serial 503526742542
[Freenect2Impl] found 1 devices
[Freenect2DeviceImpl] opening...
[UsbControl::claimInterfaces(IrInterfaceId)] failed! libusb error -6: LIBUSB_ERROR_BUSY
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] failed to open Kinect v2 @2:4!
no device connected or failure opening the default one!

**Comment by wiedemeyer** [comment]
What USB controller are you using, which kernel are you running? You might want to look into the issues on https://github.com/OpenKinect/libfreenect2 or open a new one there, because it is a libfreenect2 related issue.

**Comment by DrFuzzy** [comment]
delk@Darwin:~/libfreenect2/examples/protonect$ lspci |grep USB
00:1a.0 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #4
00:1a.1 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #5
00:1a.2 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #6
00:1a.7 USB controller: Intel Corporation 82801JI (ICH10 Family) USB2 EHCI Controller #2
00:1d.0 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #1
00:1d.1 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #2
00:1d.2 USB controller: Intel Corporation 82801JI (ICH10 Family) USB UHCI Controller #3
00:1d.7 USB controller: Intel Corporation 82801JI (ICH10 Family) USB2 EHCI Controller #1

delk@Darwin:~/libfreenect2/examples/protonect$ uname -r
3.13.0-43-generic

Thanks

**Comment by eschneider1992** [comment]
+1 same issue as @DrFuzzy / in their case it looks like they're missing a USB 3.0 hub, which I managed to fix by twiddling with BIOS settings (XHCI mode etc) and I have 3.16.0-33, and I still get LIBUSB_ERROR_BUSY, even when I run it with sudo.

**Comment by eschneider1992** [comment]
This does seem to be an upstream libfreenect2 issue I think.
