### ISSUE TITLE
[News] iai_kinect2/libfreenect2 at ICRA 2015

### ISSUE THREAD

**Issue by xlz** [code-iai/iai_kinect2#97]
Three teams at [Amazon Picking Challenge](http://amazonpickingchallenge.org/teams.shtml) on the first day used iai_kinect2/libfreenect2 for their manipulation tasks.

JSK, University of Tokyo reported overall success with less than ideal performance of pointcloud framerate being 10Hz with a GTX 780.
![20150526_123639](https://cloud.githubusercontent.com/assets/1385542/7827982/593e8e9e-03e2-11e5-83ff-e6caa9e5b66b.jpg)

MIT reported flawless success with a GTX Titan X and dual Kinect v2.
![20150526_125657](https://cloud.githubusercontent.com/assets/1385542/7827989/618345a4-03e2-11e5-937b-716002045fca.jpg)

Alten the Netherlands had linking issues with the binary ROS package and could not enable GPU processing. But they were able to work it through using CPU only processing.
![20150526_125734](https://cloud.githubusercontent.com/assets/1385542/7827992/6b86fd70-03e2-11e5-9348-101505beaa0e.jpg)

PR2 maintainer Clearpath Robotics also sets to integrate Kinect v2 in its indigo upgrade kit for PR2. They will have two people working on contributing to the driver.

**Comment by wiedemeyer** [comment]
Thanks for sharing. It's really nice to see that people from all over the world are using this software. Also interesting to see how much the individual setups differ.

**Comment by lakehanne** [comment]
Uber cool! Congrats Thiemo!
