### ISSUE TITLE
[Question] Is depth rectified before the registration?

### ISSUE THREAD

**Issue by JuantAldea** [code-iai/iai_kinect2#99]
Hello Thiemo,
I might have gotten it wrong but.. why the depth is not being rectified by the bridge before the depth registration takes place?

**Comment by wiedemeyer** [comment]
because the rectification and registration is done in one step.

**Comment by JuantAldea** [comment]
Could you please point me to the right DepthRegistrationCPU method where this (lens correction) is happening?

**Comment by JuantAldea** [comment]
Nevermind, found it, thanks!

**Comment by wiedemeyer** [comment]
It is happening [here](https://github.com/code-iai/iai_kinect2/blob/master/depth_registration/src/depth_registration_cpu.cpp#L129). The map gives for each coordinate in the rectified image the corresponding coordinate in the input image. This is then used to interpolate the values.
